### ISSUE TITLE
[QUESTION] is there a tutorial/example for updating model when I have a status_quo

### ISSUE THREAD

**Issue by mli-wish** [facebook/Ax#1032]
I read this [issue](https://github.com/facebook/Ax/issues/274) and found it really helpful. I understand there is a function,  `relativize_data`, but was wondering if there is an example that shows how to configure/update the experiment/model when I have a status quo arm, preferably while using service_api? Thanks!

**Comment by bernardbeckerman** [comment]
Hi @mli-wish, first of all, sorry for the late reply! As for your question, I believe you can provide the parameterization of the desired status-quo arm to the `status_quo` argument of `AxClient.create_experiment`, and relativization etc. should be taken care of under-the-hood. Does that help? Or am I misunderstanding and you're trying to set a status-quo arm after you've already begun the experiment? There is an `AxClient.set_status_quo()` method but that may not alter/update the OptimizationConfig accordingly. cc @danielcohenlive, who has a bit more experience with these types of experiments than I do, and also @danielrjiang the current modopt oncall.

**Comment by mli-wish** [comment]
Hi @bernardbeckerman , no worries, and thanks for your reply. Some follow up questions:

1. I understand I can specify the `status_quo` argument of `AxClient.create_experiment`. It is unclear to me what format of the raw_data should be passed to `ax_client.complete_trial()` when there are multiple arms including a status_quo arm. Please let me know if there is documentation on this but I missed it.
2. How do I set up relativization?
3. When relativizing metrics to the status quo, what are the advantages of taking a ratio (treatment/control) compared with taking a difference (treatment-control)? The SEMs are easier to calculate for the difference. On the other hand, the calculation of SEMs of the ratios needs to resort to delta approximations.
Thanks!

**Comment by jelena-markovic** [comment]
Hi @mli-wish, `Relativize` transform from [https://ax.dev/api/_modules/ax/modelbridge/transforms/relativize.html#Relativizetransforms](https://l.facebook.com/l.php?u=https%3A%2F%2Fax.dev%2Fapi%2F_modules%2Fax%2Fmodelbridge%2Ftransforms%2Frelativize.html%23Relativizetransforms&h=AT2GN7reJ_TU253Bi9HZ1fkLnkzQcpi7aBIfrzx5zyEPwycbUSYGqIZne3rcFQC7BqKYCN2Ydf27RVE_3ZLXA5COyBDOFnrqMYRWyhov2YCWA-IWnku8B5l1QXkkb7ldobjxSQ6mfhA) your data so that the effects and their standard errors are with respect to the status quo/control group. `Relativize` computes the effects as the ratios (test group effect - control group effect)/control group effect and it performs delta method on your data so it computes the standard errors for these ratios. 

The way you would use this in modeling is by specifying `transforms=[Relativize]` (with potentially other transforms) argument in ModelSetup [https://ax.dev/api/_modules/ax/modelbridge/registry.html#ModelSetup](https://l.facebook.com/l.php?u=https%3A%2F%2Fax.dev%2Fapi%2F_modules%2Fax%2Fmodelbridge%2Fregistry.html%23ModelSetup&h=AT2GN7reJ_TU253Bi9HZ1fkLnkzQcpi7aBIfrzx5zyEPwycbUSYGqIZne3rcFQC7BqKYCN2Ydf27RVE_3ZLXA5COyBDOFnrqMYRWyhov2YCWA-IWnku8B5l1QXkkb7ldobjxSQ6mfhA). The latter file has many examples with different transforms used. For this to work, as you said you'd need to set up the `status_quo` test group/arm for your experiment. 

Specifying the transform would fit the model to the relativized values (ratios) and not absolute. This might indeed give different model fit and it might be worth trying. But it is usually fine to just fit models to absolute data and relativize data afterwards for presentation purposes as the relative differences between test and control might be more interpretable than absolute differences for some applications.

**Comment by lena-kashtelyan** [comment]
> The way you would use this in modeling is by specifying transforms=[Relativize] (with potentially other transforms) argument in ModelSetup [https://ax.dev/api/_modules/ax/modelbridge/registry.html#ModelSetup](https://l.facebook.com/l.php?u=https%3A%2F%2Fax.dev%2Fapi%2F_modules%2Fax%2Fmodelbridge%2Fregistry.html%23ModelSetup&h=AT2GN7reJ_TU253Bi9HZ1fkLnkzQcpi7aBIfrzx5zyEPwycbUSYGqIZne3rcFQC7BqKYCN2Ydf27RVE_3ZLXA5COyBDOFnrqMYRWyhov2YCWA-IWnku8B5l1QXkkb7ldobjxSQ6mfhA). The latter file has many examples with different transforms used. For this to work, as you said you'd need to set up the status_quo test group/arm for your experiment.

Just to further elaborate on this, in Service API, you would add the `Relativize` transform to your generation strategy. This snippet shows how to customize a generation strategy: https://ax.dev/tutorials/generation_strategy.html#1A.-Manually-configured-generation-strategy. You would want to add a "transforms" key to the `model_kwargs` input dictionary, and point it to the value `[Relativize] + Cont_X_trans + Y_trans`. Something very similar is done here: https://github.com/facebook/Ax/blob/668caded911a0ca6e461bea7b8e14caef6f18ded/ax/modelbridge/dispatch_utils.py#L89, except with `Winsorize` instead of `Relativize`. 

You'd only need to do this for the Bayesian optimization step of the generation strategy also; Sobol does not learn from data so the relativization does not matter there. Let us know whether that works for you!

**Comment by lena-kashtelyan** [comment]
Closing this as inactive; please reopen if you follow up, @mli-wish!
