### ISSUE TITLE
Standard error or standard deviation?

### ISSUE THREAD

**Issue by crasanders** [facebook/Ax#1036]
https://github.com/facebook/Ax/blob/fa3e90587889b5c1aa3ca4cfb4aca82ca2bbd1b3/ax/modelbridge/prediction_utils.py#L16-L41

The documentation for `predict_at_point` says at the top that it returns the mean and standard _deviation_, whereas at the bottom it says mean and standard _error_. My reading of the code is that it returns the standard deviation (the square root of the variance). Other functions which depend on this one also reference the standard error, though. Which statistic is intended to be returned here?

**Comment by Balandat** [comment]
It returns the standard deviation. Ax is a bit sloppy about terminology in some places, largely b/c historically it has been used a lot in the context of field experiments where we have variance estimates for each observation (the observation here is the sample mean, and the standard deviation of that is the SEM, so sometimes you will see SEM used instead of standard deviation). We should clean this up and make things consistent and unambiguous throughout the codebase.

**Comment by pcanaran** [comment]
Closing this issue. @crasanders please feel free to reach out again if you have additional questions.
