### ISSUE TITLE
[Question] Thoughts on using Ax for stochastic trials

### ISSUE THREAD

**Issue by Padarn** [facebook/Ax#1195]
This is a fairly open an vague question apologies, but I'd like to see if anyone has thoughts on using the approach implemented by Ax for "stochastic trials", or stated another way "policy learning".

What I mean by this is instead of running a trial with a fixed set of parameters, it is common in reinforcement learning to deploy a stochastic policy (for example a policy defined to output a value from a parameterized distribution). This allows for applying algorithms like REINFORCE.

I am trying to understand if there is a bridge between these two approaches which is useful. One way of modelling this would be to just have the `Trial` define the parameters of a stochastic policy. This seems okay, but applying the rest of the BO toolbox to this kind of data seems tricky.

Any thoughts from people using Ax?

**Comment by Balandat** [comment]
Since you are trying to optimize the policy I think the most natural thing to do is to use the parameters of the parameterized policy as the trial parameters. 

How many evaluations are you planning to do? In RL typically you'll have a lot more than in standard BayesOpt settings and you will likely hit scalability limits  in Ax itself if you ran thousands or tens of thousands of trials. 

If you have a stochastic policy what would make sense would be to, within a trial, sample repeatedly from. The parameterized policy and then aggregate the results as the performance metric of the trial (eg compute mean and variance, ideally such that a normal approximation is reasonable).

**Comment by Padarn** [comment]
You're right, I'm thinking of scenarios in which the number of trials grows very large (but observations may be very noisy). Perhaps this does not fit very well into the BayesOpt framework.

> If you have a stochastic policy what would make sense would be to, within a trial, sample repeatedly from. The parameterized policy and then aggregate the results as the performance metric of the trial (eg compute mean and variance, ideally such that a normal approximation is reasonable).

hmm, in this case there might be little advantage in using a stochastic trial - you would be averaging out the effect (or biasing the estimate)

Am I just mixing approaches here were there is no particular link?

**Comment by Balandat** [comment]
Yeah it seems that you're interested in settings where individual evaluations of your black box function that you're trying to optimize are quite cheap, which is a setting BO isn't exactly designed for. 

In terms of connections, things we've done successfully in the past is "reward shaping" for RL - i.e. parameterized the reward function and then run an RL algo for that, observe some other metrics from deploying the RL policy (e.g. in an A/B test), and then apply BO on top of that over the parameterization of the reward function.

**Comment by Padarn** [comment]
You're completely right. Evaluation is cheap, but potential correlated across evaluations (which is why BO was the initial thought).

Interesting thought on reward shaping. I'll need to think a bit more about it. It sounds very sensible but perhaps not immediately necessary.

**Comment by Balandat** [comment]
Cool. Closing this out for now then, feel free to reopen if needed.
