### ISSUE TITLE
Using the AxClient on discrete excel grid

### ISSUE THREAD

**Issue by Mahadi2244** [facebook/Ax#1215]
Is there a way to implement the AxClient on a discrete excel search space using the ServiceAPI? Would adding choice parameter for all the parameters be a correct approach to handle this?

**Comment by Balandat** [comment]
Could you be more precise what a "discrete excel search space" is? What are the parameters here? Are the parameters actually discrete or even categorical? Or are they numerical but you cannot evaluate anything that isn't already contained in your data / spreadsheet? (and if that's the case, can you just look up the outcome(s) as well, or do you need to perform a reasonably expensive evaluation?)

**Comment by Mahadi2244** [comment]
Thanks for the reply Balandat. I have grid space of 1023 rows and 17 columns. All the columns are design parameters of a prototype and it is an expensive to evaluate blackbox function. The parameter are numerical discrete variables. For example x1 takes values like {1.77, 2.7, 2.84, 4.43, 7.85,11.27}. The combination of the values for each  of these variable gives me 1023 rows. The outcome variable is numerical continuous variable which determines the quality of the prototype developed using a set of features. 
I was able to attach the previously completed trials with my AxClient() but not sure after how can the acquisition function be implemented on this grid?
 I was thinking If creating choice variables for each of the 17 columns would be the right approach or could I somehow pass the grid to the Axclient()?
Thanks for the help!

**Comment by Balandat** [comment]
So you're getting the 1023 rows by enumerating all possible combinations between the feature values? Is this the full combination (i.e. X1 x X2 x ... x X17) or are there certain combinations that are not permissible (asking since 1023 seems low for O(k^17)). 

At a high level we don't want to encode each possible choice as a possible choice of a ChoiceParameter - doing that would remove all the structure from the problem and not really allow our model-based approaches to learn anything. Instead, what you'd want to do is encode each of the numerical parameters as its own *ordered* choice parameter (setting `is_ordered=True`).

**Comment by Mahadi2244** [comment]
There are certain combinations that are not permissible based on the domain knowledge, so I have removed them from the grid file which helped me reduce the search space size to 1023 rows. 
I will encode all the numerical parameters as its own ordered choice parameter then?

**Comment by Balandat** [comment]
> I will encode all the numerical parameters as its own ordered choice parameter then?

So that would give the full product search space rather than the one you have filtered to 1023. I think in this case the most reasonable thing to do is to use float parameters for the modeling, but then select the next candidates by evaluating the acquisition function on the 1023 permissible combinations. That way you a proper model that doesn't artificially encode what are fundamentally continuous parameters, but only consider the combinations that make sense. 

So you'd define your search space as continuous, start off with some random points from the list and compute the metrics  and pass that data to the experiment (either via the Dev or service API), and then use https://github.com/facebook/Ax/blob/main/ax/modelbridge/torch.py#L371 to select the next candidate to evaluate from your list. There is a related discussion & additional context in #771

**Comment by lena-kashtelyan** [comment]
@Mahadi2244, is this issue still active or did you get a full answer to your questions?

**Comment by pcanaran** [comment]
@Mahadi2244, I'll go ahead and close this issue. Please feel free to reach out again if you have further questions. 

cc @lena-kashtelyan, @Balandat
