### ISSUE TITLE
Updating Botorch Model requires positional Argument Search Space Suggest

### ISSUE THREAD

**Issue by aegonwolf** [facebook/Ax#1257]
Hi All, I am quite new to both Ax and Botorch and have been fighting through the tutorials.

I now tried to update the Botorch Model as mentioned on the tutorial Page appendix 1 at the very bottom:
https://ax.dev/tutorials/modular_botax.html 
When I call `BoTorchModel.update([self.xs, self.fs], metric_names = "f")` I get that it needs a positional argument SearchSpaceDigest.

Could someone explain to me what I have to add or how can I update the model with new datapoints not suggested by trials?
Thank you very much!

**Comment by pcanaran** [comment]
Thank you for reaching out @aegonwolf. I'm checking with the team to find someone who can elaborate/provide examples on this.

**Comment by saitcakmak** [comment]
Hi @aegonwolf. You should not be interacting with Ax Models directly. Instead of calling `BoTorchModel.update` you should instead use the ModelBridge APIs. In this case, `ModelBridge.update` is what you're looking for: https://github.com/facebook/Ax/blob/707aa86fcbeb0eabb132ae9911a29e5f563a00e4/ax/modelbridge/base.py#L556
It will internally construct the `SearchSpaceDigest` and other necessary arguments and pass them down to the model. This will also make sure that the transforms are applied to the inputs before updating.

**Comment by aegonwolf** [comment]
> Hi @aegonwolf. You should not be interacting with Ax Models directly. Instead of calling `BoTorchModel.update` you should instead use the ModelBridge APIs. In this case, `ModelBridge.update` is what you're looking for:
> 
> https://github.com/facebook/Ax/blob/707aa86fcbeb0eabb132ae9911a29e5f563a00e4/ax/modelbridge/base.py#L556
> 
> It will internally construct the `SearchSpaceDigest` and other necessary arguments and pass them down to the model. This will also make sure that the transforms are applied to the inputs before updating.

I see, thanks for that!
