### ISSUE TITLE
Multi timescale metrics? 

### ISSUE THREAD

**Issue by AustinGomez** [facebook/Ax#1268]
Hi AX team,

Is it possible to have metrics that arrive at different time periods? E.G. in a Field Experiment, I want to maximize immediate CTR given that 14 day retention stays above some threshold. 

I figure I can implement this in my retention metric subclass and have the metric only report its data at the time interval. I'm wondering if there's a better way to do this, and also wondering if I'll run into any issues with the GPEI and EBTS model implementations? I would expect there to be impact to theoretical regret bounds but that should be ok for my use case. Ideally I'm looking to use multi timescale metrics as either objectives or (more importantly) a guardrail constraints.

Btw, thanks for building such a robust and useful tool.

Austin

**Comment by Balandat** [comment]
@qingfeng10 this is right up your alley!

**Comment by lena-kashtelyan** [comment]
Hi @AustinGomez, sorry it took us a while to get back to you! I'm not the right person to help with this, but let me make sure someone gets back to you next week.

**Comment by Balandat** [comment]
@AustinGomez, apologies that this fell off the radar right before the holidays. 

Your immediate approach makes sense - you can mix and match short-term and long-term metrics in the optimization. 

How much correlation is there between these metrics (say CTR and retention)? If there is a lot then taking this into account in the modeling with a multi-task model would be a first step towards a more sophisticated approach.

If you have more granular time series data such as the fraction of users retained as a function of the time since exposure, then one could do more sophisticated things with time series modeling also (@danielrjiang has done a good amount of that in the context of learning curve prediction for AutoML applications, but similar approaches should in generally also be applicable in the field experiment context).

**Comment by qingfeng10** [comment]
Hey @AustinGomez, apologize for chiming late here. What Max's suggestions above makes a lot sense and here are couple more points added to that. 

The main constraint (14 days retention) has a at least 14 days latency given the definition. The simplest but time-consuming solution is to wait for 14 days, compute CTR and maximize that sequentially. A faster way (the motivation to use multi time scale definition of retention) is to use 3-days, 5-days retention or more sophisticated surrogates (ML-based) as a short-term proxies. You can conduct some correlation analysis to understand how predictive these proxies are. If they are informative, you can use these proxies instead. 

There is no implementation concern here (you can define these proxies as a new metric and model/optimize them via GPEI). The main concern comes from the potential bias from these proxies.  Therefore, echoing Max's point above, a faster and better way is to leverage multi-task model and a new experiment design to correct bias from short-term proxies. Long story short, you can run two online experiments (each contains a set of test group) that one of them will keep running for more than 14 days to observe the true long-term outcomes and the other one will run rapid iterations based on and a multi-task model to combine short-term retentions data e.g. 3-5 days and longer-term data. By doing so, you will rapidly explore the space and project the short-term data to longer-term based the multi-task model. We currently don't have a tutorial for this algorithm yet; if you are interested in, we can prioritize on releasing it next year.

**Comment by pcanaran** [comment]
Hi @AustinGomez. Do you have any other questions? If not, I'll go ahead and close this issue.

**Comment by pcanaran** [comment]
Closing this issue. @AustinGomez please feel free to reach out again if you have further questions.
