### ISSUE TITLE
Service API: Updating model with only new data

### ISSUE THREAD

**Issue by nob776** [facebook/Ax#1329]
Hello,
I'm using an external, stateful model in a TorchModelBridge. When using ``GenerationStep.use_update=true``, I expected my custom model's ``update`` method to be called with only new data. However, it is called with *all* the data, because ``ModelBridge.update`` tacks the new data along with all the old data and sends it to ``ModelBridge._update``. Is this intentional? It looks to be incorrect behavior based on the documentation and how I'm reading the test_generation_strategy.py test case.

Thanks!

**Comment by pcanaran** [comment]
Thank you @nob776 for reaching out. I'll review with the team and get someone who can help with your question. In the meantime can you please share any code that demonstrates the issue?

**Comment by lena-kashtelyan** [comment]
Hello @nob776! `GenerationStrategy` does indeed only send new data to `ModelBridge.update`, but `ModelBridge.update` joins it with pre-existing data and sends that to `_update`: https://github.com/facebook/Ax/blob/c4d298918068c55d336bc27a635409f52baefa0c/ax/modelbridge/base.py#L571-L581.

I do realize this is a bit strange; I know @bletham has a great explanation of why things are this way.

If you do need just the new data, you will need to define your own extension of `TorchModelBridge` most likely, in which you can override the `update` method from the base `ModelBridge` and skip the `_extend_training_data` call. Alternatively, you can keep track of "seen" data in the `Model` class and filter the data it gets on `update`.

**Comment by nob776** [comment]
That makes sense, thank you @lena-kashtelyan.

**Comment by bletham** [comment]
To give a little context for this, the behavior is on its surface a bit odd. GenerationStep takes only new data. ModelBridge.update also expects only new data:

https://github.com/facebook/Ax/blob/9d0f93eb809b683f501589e19a0c92d11e5fb756/ax/modelbridge/base.py#L561-L562

But, at the next layer, ModelBridge hands the data over to TorchModel, which expects all data:

https://github.com/facebook/Ax/blob/9d0f93eb809b683f501589e19a0c92d11e5fb756/ax/models/torch_base.py#L218-L219

So why does TorchModel expect all of the data instead of just the new data. The reason is because of transforms. Some transforms in the ModelBridge depend on the data, for instance, StandardizeY will standardize the Y values by subtracting the mean and dividing by the std. At model fitting is when the mean and std of Y are computed from the data and stored in the transform. Winsorization is another example where the limits of Winsorization are computed from the data. If the limits are computed only from the initial data and then kept constant through the whole optimization, this can cause bad behavior. For instance, if the first data given into `fit` did not have any outliers, the winsorization limits may be set way too tightly and so they will need to be updated as subsequent data with outliers are passed in.

So, in order for data transformations to work well, the transforms must be updated when the data are updated. That happens here:
https://github.com/facebook/Ax/blob/9d0f93eb809b683f501589e19a0c92d11e5fb756/ax/modelbridge/base.py#L572-L577

But if I change the transforms, I have to re-apply the new transform to all of the old data. For instance, changing a winsorization limit means that some of the data that was winsorized in my original dataset may no longer be; Or changing the standardization mean will shift all of the data. And so when we update the model with some additional data, the transforms are updated which potentially changes all of the transformed data that are sent to TorchModel. And that is why it expects all of the data.
