### ISSUE TITLE
how to declare search space bounds with step

### ISSUE THREAD

**Issue by academe-01** [facebook/Ax#1434]
Hello,

        parameters=[
          {
            "name": "x1",
            "type": "range",
            "bounds": [-10.0, 10.0],
          },

is there a way to set stepping ?
for example             "bounds": [-10.0, 10.0], step: 0.5.  ?

**Comment by bernardbeckerman** [comment]
First, please make sure that your use-case requires discrete parameter values. Valid reasons to use discrete values include encoding some domain knowledge particular to your system, e.g., only certain values are allowed by your system, or certain values (e.g., powers of two) are consistently more efficient than others. Invalid reasons include wanting to shrink the search space to something more searchable, since shrinking the search space in this way does not help the search but instead keeps it from trying intermediate parameter values that could yield better results.

If you do require discrete parameter values, you can achieve this with Choice Parameters by setting the `values` argument to whatever series you like (e.g., defined via a `range` function). When doing this, make sure to also set `is_ordered=True`, which will ensure Ax takes into account the ordering of the parameter values (e.g., if your parameter values are `["a", "b", "c"]`, Ax will consider `"a"` closer to `"b"` than to `"c"`). Hope that helps!

**Comment by Balandat** [comment]
Another thing you can do is do the transformation on your end - e.g. in this case define the parameter as in Integer parameter with 20/0.5+1 = 41 values that are mapped to the respective values in your code as `your_param = -10 + 0.5 * ax_param`.

**Comment by bernardbeckerman** [comment]
@academe-01 closing this out since there hasn't been any activity in a while but please let us know if you would like further assistance and I'll be happy to open back up!
