### ISSUE TITLE
Unexpected shape in posterior pareto front

### ISSUE THREAD

**Issue by acse-itk22** [facebook/Ax#1560]
I am working on a structural optimisation problem and I have generated a posterior pareto front (with compute_posterior_pareto_frontier). I imposed the pareto front points from actual evaluations (generated using `ax_client.get_pareto_optimal_parameters(use_model_predictions=True)`). 
```
frontier = compute_posterior_pareto_frontier(
    experiment=self.experiment,
    data=self.experiment.fetch_data(),
    primary_objective=self.objective.objectives[0].metric,
    secondary_objective=self.objective.objectives[1].metric,
    absolute_metrics=objective_names,  # we choose all metrics
    num_points=100,  # number of points in the pareto frontier
)
```
I am finding it very difficult to interpret the results. Is there any way you could help? For context, I was using objective function evaluations from FEA with noise in the evaluation function set to 0.0.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/112338249/228907518-70a47859-438e-4dcf-86ce-fab019b1b8cb.png">
<img width="478" alt="image" src="https://user-images.githubusercontent.com/112338249/228907596-4607d1ec-e13c-48c2-800c-636e65a74591.png">

**Comment by Balandat** [comment]
Hmm so the bottom right part of the PF seems fine to me and general matches the shape of the observed trials in later iterations. I am not quite sure what's happening in the left half though (kind of hard to see b/c the top is covered by the legend). Is that part also what concerns you? This could be due to some numerical/optimization issues with tracing out the frontier by means of computing posterior means.

**Comment by lena-kashtelyan** [comment]
@acse-itk22 it seems to me that your question was answered, so I'm closing this issue. Please feel free to follow up on it, but if you do, please reopen the issue as we might not see your comment on a closed one.
