### ISSUE TITLE
Service API: How to properly load from json?

### ISSUE THREAD

**Issue by torayeff** [facebook/Ax#1565]
I want to save ax_client to JSON and later load it from another python file to analyze it. The code below
```
from ax.service.ax_client import AxClient, ObjectiveProperties
from ax.utils.notebook.plotting import render

ax_client = AxClient()
total_trials = 50

ax_client.create_experiment(
    name="drilling_experiment",
    parameters=[
        {
            "name": "x",
            "type": "range",
            "bounds": [-5, 5],
            "value_type": "float",
        },
        {
            "name": "y",
            "type": "range",
            "bounds": [-5, 5],
            "value_type": "float",
        },
    ],
    objectives={"obj": ObjectiveProperties(minimize=True)},
)


def evaluate(parameters):
    x = parameters["x"]
    y = parameters["y"]
    return (x**2 + y - 11) ** 2 + (x + y**2 - 7) ** 2


for i in range(total_trials):
    parameters, trial_index = ax_client.get_next_trial()
    print(f"Trial index: {trial_index}".center(50, "-"))
    for k, v in parameters.items():
        print(f"{k} = {v}")
    ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))

ax_client.save_to_json_file()
ax_client = AxClient.load_from_json_file()
render(ax_client.get_contour_plot())  # this gives error!
```

gives the following error:
```
raise UnsupportedPlotError(
ax.exceptions.core.UnsupportedPlotError: Could not obtain contour plot of "obj" for parameters "x" and "y", as a model with predictive ability, such as a Gaussian Process, has not yet been trained in the course of this optimization.
```

It works when I directly render within the same script without saving the ax_client.

**Comment by mpolson64** [comment]
Thank you for reaching out. This is expected behavior but could probably do to have a more informative error message here -- I'll see if I can prioritize getting something better in by the next patch release.

Here's what's going on: AxClient does not have a fitted internal model at load time, and thus is unable to create any plots that need a fitted model under the hood. We don't save the fitted model because it could be large (and saving torch objects can have various implications with regard to backwards compatibility), and we don't fit a new model at load time because this can be very computationally expensive for our more complex models or if there have been many arms in the experiment. Because model fitting is so expensive we only rarely do it silently under the hood, and instead have the user manually call `ax_client.fit_model()` when necessarily. If you instead do the following things should work perfectly:
```
ax_client = AxClient.load_from_json_file()
ax_client.fit_model()
render(ax_client.get_contour_plot())
```

Let me know if this solved your issue or if you have any other questions.

**Comment by torayeff** [comment]
Thanks for a very good explanation of the issue! It works now with fitting!
