### ISSUE TITLE
Outcome Constraint Including Standard Deviation

### ISSUE THREAD

**Issue by theonlydvr** [facebook/Ax#1705]
I am using Ax with the Service API to solve a multi-objective optimization problem where two of the objectives are directly related to the experiment while a third is explicitly relevant to safety/side effects. From my understanding, this third objective would be well suited for an ObjectiveConstraint. However, it is rather important that the optimizer initially avoids unsafe values for these objectives and only slowly expands the search space as the edges are deemed safe. I've previously seen this done by incorporating a scaled version of the outcome standard deviation as part of the constraint: [https://doi.org/10.1007/s10994-021-06019-1](url).
So the constraint would be something along the lines of: `metric + 2*metric_std >= 0`
 Is it possible to implement such a constraint in Ax and if not, is this something that could be done with BoTorch?

Edit: From some further experimentation and it looks like ObjectiveConstraints on noisy metrics generally seem to prevent sampling of parameters that have around a 50% chance of violating the constraints. Can the balance of maximizing expected improvement and preventing constraints from being violated be tuned in any way? 
From what I understand, for an MCMC sampler, the constraint is applied to each posterior draw separately where the acquisition function is multiplied by a sigmoid based on the constraint (bringing the acquisition function for the draw to approximately 0 if it violates the constraint). The adjusted draws are then averaged together to produce the full acquisition function. Would it be possible to instead apply the constraint to all the draws at once by including a factor for the acceptable probability of violating the constraint?

**Comment by saitcakmak** [comment]
Hi @theonlydvr. Ax supports specifying outcome constraints on a metric or a linear combination of multiple metrics. If you observe `metric_std` along with `metric`, you could provide this to Ax as a separate metric and define the constraint `metric + 2*metric_std >= 0` using `ScalarizedOutcomeConstraint`. Otherwise, this is not currently supported in Ax.

>  is this something that could be done with BoTorch?

Yes. While Ax is constrained by serializability limitations, BoTorch supports constraints that are expressed using arbitrary callables. For multi-objective optimization, we use qNEHVI acquisition function, which supports callable constraints: https://github.com/pytorch/botorch/blob/main/botorch/acquisition/multi_objective/monte_carlo.py#L403-L407

> Can the balance of maximizing expected improvement and preventing constraints from being violated be tuned in any way?
> Would it be possible to instead apply the constraint to all the draws at once by including a factor for the acceptable probability of violating the constraint?

I believe these would require customizing the BoTorch components but they should be doable if you're comfortable with defining customized acquisition functions. You can also use custom BoTorch acquisition functions in Ax following this tutorial: https://botorch.org/tutorials/custom_acquisition

**Comment by lena-kashtelyan** [comment]
Hi @theonlydvr! Please let us know if the answer @saitcakmak gave above is not exhaustive/if there is still something you are wondering. Please reopen the issue if you follow up, as we are unlikely to see comments on a closed issue.
