### ISSUE TITLE
What are the model_kwargs for ax.Models.GPEI

### ISSUE THREAD

**Issue by smao-astro** [facebook/Ax#1710]
Dear developers and contributors,

I'm a newcomer to Ax and would like to express my gratitude for your work in developing this remarkable package and making it publicly available.

I am interested in understanding the possible configuration options for the `model_kwargs` parameter when calling `ax.Models.GPEI` with `ax.modelbridge.generation_strategy.GenerationStep`. My existing code has been adapted from one of your tutorials.

```
    gs = ax.modelbridge.generation_strategy.GenerationStrategy(
        steps=[
            # 1. Initialization step (does not require pre-existing data and is well-suited for
            # initial sampling of the search space)
            ax.modelbridge.generation_strategy.GenerationStep(
                model=ax.Models.SOBOL,
                num_trials=args.n_initial_points,  # How many trials should be produced from this generation step
                min_trials_observed=args.n_initial_points,  # How many trials need to be completed to move to next model
                max_parallelism=args.max_parallelism_sobol,  # Max parallelism for this step
                model_kwargs={
                    "seed": args.key,
                },  # Any kwargs you want passed into the model
                model_gen_kwargs={},  # Any kwargs you want passed to `modelbridge.gen`
            ),
            # 2. Bayesian optimization step (requires data obtained from previous phase and learns
            # from all data available at the time of each new candidate generation call)
            ax.modelbridge.generation_strategy.GenerationStep(
                model=ax.Models.GPEI,
                num_trials=-1,  # No limitation on how many trials should be produced from this step
                max_parallelism=args.max_parallelism_bayesopt,  # Parallelism limit for this step, often lower than for Sobol
                # More on parallelism vs. required samples in BayesOpt:
                # https://ax.dev/docs/bayesopt.html#tradeoff-between-parallelism-and-total-number-of-trials
                model_kwargs={
                    "torch_dtype": torch.double,
                    "torch_device": DEVICE,
                },
            ),
        ],
    )
    ax_client = ax.service.ax_client.AxClient(generation_strategy=gs)
```

I'm under the impression that the Service API permits me to customize settings for the kernel, the acquisition function, or the optimizer for the acquisition function. I believe this can be achieved by simply passing keyword arguments to the `model_kwargs` of `ax.modelbridge.generation_strategy.GenerationStep`. If this assumption is incorrect, please feel free to correct me.

My primary query is about finding documentation that can guide me on what keyword arguments I can pass in. Is this something unique to Ax, or should I refer to the BoTorch documentation?

Looking forward to your guidance.

Thanks.

**Comment by lena-kashtelyan** [comment]
Hi @smao-astro! There are many possible `model_kwargs`, don't think these are listed exhaustively anywhere. 

> the Service API permits me to customize settings for the kernel, the acquisition function, or the optimizer for the acquisition function

This is correct, but only when you are using `Models.BOTORCH_MODULAR`, following this tutorial: https://ax.dev/tutorials/modular_botax.html. Similar customizations are not easy with `Models.GPEI`, which still uses our legacy setup currently (soon to be migrated, but not yet done).

> I believe this can be achieved by simply passing keyword arguments to the model_kwargs of ax.modelbridge.generation_strategy.GenerationStep

This is exactly right; `model_kwargs` you specify here will be passed down as `Models.BOTORCH_MODULAR(**model_kwargs)`, which passes them to this function: https://github.com/facebook/Ax/blob/a692ea8a246d9c9c1033d40d66ca2f59aa66fa0d/ax/modelbridge/registry.py#L323. To know which `Model` and `ModelBridge` classes a given `Models` enum entry will ultimately use, you can look for the key in the enum, then value corresponding to that key in this dictionary: https://github.com/facebook/Ax/blob/a692ea8a246d9c9c1033d40d66ca2f59aa66fa0d/ax/modelbridge/registry.py#L172-L177.

`ModelRegistryBase.__call__` (this is what gets called when you call e.g. `Models.BOTORCH_MODULAR(...)`) separates the `model_kwargs` into arguments to `ModelBridge` and `Model` classes (in this case, `TorchModelBridge` and `ModularBoTorchModel`: https://github.com/facebook/Ax/blob/a692ea8a246d9c9c1033d40d66ca2f59aa66fa0d/ax/modelbridge/registry.py#L172-L177) based on they keyword name: https://github.com/facebook/Ax/blob/a692ea8a246d9c9c1033d40d66ca2f59aa66fa0d/ax/modelbridge/registry.py#L347-L390. It's fairly complicated, but ultimately it means that `GenerationStep.model_kwargs` can contain any and all arguments that will be passed to `TorchModelBridge` or `BoTorchModel` (imported as `ModularBoTorchModel` in registry.py above, note the aliasing) constructors, together in one dictionary.

So that would be these arguments to `TorchModelBridge.__init__`: https://fburl.com/0p2e8fq3 and arguments to `BoTorchModel.__init__`: https://fburl.com/x2jw9wou, if you are using `Models.BOTORCH_MODULAR`. 

If you use `Models.GPEI`, it will be the same model bridge, but this legacy model class instead: https://github.com/facebook/Ax/blob/a692ea8a246d9c9c1033d40d66ca2f59aa66fa0d/ax/models/torch/botorch.py.

Hopefully this fully answers your question!

**Comment by lena-kashtelyan** [comment]
Hi @smao-astro! Please let us know if the answer I gave above is not exhaustive/if there is still something you are wondering. Please reopen the issue if you follow up, as we are unlikely to see comments on a closed issue.
