### ISSUE TITLE
Why experiment.fetch_data() or get_GPEI(experiment=experiment, data=experiment.fetch_data()) re-run all experiment?

### ISSUE THREAD

**Issue by StanleyYoo** [facebook/Ax#1790]
Hi,

Many thanks for your support in advnace:)

I am running external simulation via Simulink and train via below code:

```
for i in range(NUM_BOTORCH_TRIALS):
    print(f"Running GP+EI optimization trial {i + NUM_SOBOL_TRIALS + 1}/{NUM_SOBOL_TRIALS + NUM_BOTORCH_TRIALS}...")
    # Reinitialize GP+EI model at each step with updated data.
    gpei = Models.BOTORCH(experiment=exp, data=exp.fetch_data())
    generator_run = gpei.gen(n=1)
    trial = exp.new_trial(generator_run=generator_run)
    trial.run()
    trial.mark_completed()
    save_experiment(exp, filepath, encoder_registry=bundle.encoder_registry)
```

after the train session, reload the trained model and inference with folloinwg code:

```
exp = load_experiment(filepath, decoder_registry=bundle.decoder_registry)
m = get_GPEI(experiment=exp, data=exp.fetch_data())
gr = m.gen(n=5, optimization_config=optimization_config)
obs_feats = [
    ObservationFeatures(
        parameters={"x0": 0.15210798, "x1": 0.41137701, "x2": 0.21767251, "x3": 0.45381525, "x4": 0.55131876, "x5": 1.0}
    ),
    ObservationFeatures(
        parameters={"x0": 0.75144396, "x1": 0.76591609, "x2": 0.95522241, "x3": 0.54012577, "x4": 0.46761107, "x5": 1.0}
    ),
]
f, cov = m.predict(obs_feats)
print(cov)
print(f)
render(
    plot_contour(
        model=m,
        param_x="x0",
        param_y="x1",
        metric_name=metric_name,
    )
)
```

What I found is it keep re-simulating all trained cases again. Does `save_experiment(exp, filepath, encoder_registry=bundle.encoder_registry)` means save the entire trained model and `exp = load_experiment(filepath, decoder_registry=bundle.decoder_registry)` load the trained model so I can keep training or inferencing?

Look forward to hearing from you,
Stanley

**Comment by Balandat** [comment]
How are you defining your Metrics, the Runner,  and the experiment? At a high level the idea is that the Runner kicks off evaluation, which then stores the results somewhere, and the metric fetches the results form. My guess is that you instead set things up in a way where the Metric itself actually runs the simulation (rather than just looking up the data)? 

If you don't need to run complex orchestration with asynchronous remote evaluation, it might be easier to use the Service API in your case. That provides a simple ask/tell interface and the experiment doesn't actually know how to run the evaluation (you need to provide that to the AxClient). Check it out here: https://ax.dev/tutorials/gpei_hartmann_service.html

**Comment by lena-kashtelyan** [comment]
+1 to @Balandat in that the problem is likely in how you define your `Metric`. A couple questions:

1. Is your `Metric` a subclass of `NoisyFunctionMetric`? That `Metric` subclass sets `is_available_while_running()` to return `True`: https://fburl.com/d5r8sclg, which causes the metric to be recomputed on every call to `fetch_data(). The easiest fix will likely be to override that method on your `Metric` class to return `False` from that method. The optimal one would probably be to not use `NoisyFunctionMetric`, as that one is really meant for synthetic and cheap functions. For your case defining a custom `Metric` subclass might be a better move.
2. Is there a specific reason why you are not using the Service API (`AxClient`)? You would probably find it easier and more intuitive. Here is the tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html. This would our recommended path.

**Comment by lena-kashtelyan** [comment]
Closing this as inactive. @StanleyYoo , if you still need help, please reopen the issue and follow up. We're unlikely to see your follow-up if you don't reopen : )
