### ISSUE TITLE
how to set train_yvar with A/B testing data, if i use the FixedNoiseGP model

### ISSUE THREAD

**Issue by cyrilmyself** [facebook/Ax#1812]
My goal is to optimize parameter for A/B experiments.  Since the metric is noisy, I need to use fixed noise GP with qNEI to get multiple candidate points to use for my next round of experiment. 
But i do not know how to set train_yvar parameter if i use FixedNoiseGP,
please tell me to set it

**Comment by cyrilmyself** [comment]
i need help

**Comment by esantorella** [comment]
Hi, you're right that in the context of an A/B test, it will be best to pass in the variance of the observations. You would need to compute that yourself based on the data from your underlying A/B test data. The exact format that Ax needs depends on how you're interfacing with Ax.

If you're using `AxClient` (as in the [Service API Tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html)), you would need to pass in data in (mean, standard-error-of-mean) format. In place of the `evaluate` function in that tutorial, you might have something like this:

```python
import numpy as np
import pandas as pd

def fetch_data_from_experiment(parameters) -> pd.DataFrame:
    """Get A/B test data from wherever it is stored and return
    a Pandas DataFrame where the rows are at the user level
   and each column is a different outcome."""
   # your implementation here

def evaluate(parameters):
    """
    Use something like this in place of the `evaluate` function in the tutorial.
    """  
    user_level_data = fetch_data_from_experiment(parameters)
    n = len(user_level_data)
    data = {
        outcome: (
            user_level_data[outcome].mean(),
            # standard error of the mean (sem)
            user_level_data[outcome].std() / np.sqrt(n + 1)
        )
        for outcome in user_level_data.columns
    }
    return data
```

If you're using `FixedNoiseGP`, you need to pass a variance rather than a standard error -- the square of the "sem" computed above.

If that's not clear, could you share some code to show us how you're using Ax?

**Comment by cyrilmyself** [comment]
hi，@esantorella，thanks for you relaying。The user_level_data you mentioned above is the relative difference from control group and experiment group with different observed time windows？

**Comment by cyrilmyself** [comment]
hi，@esantorella, I use service API, i do not know how to set the train_Yvar with FixedNoiseGP


gs = GenerationStrategy(
        steps=[
            GenerationStep(
                model=Models.SOBOL,
                num_trials=10,  
                min_trials_observed=10,
                max_parallelism=10,  
                model_kwargs={"seed": 999}, 
                model_gen_kwargs={},  
            ),
            GenerationStep(
                model=Models.BOTORCH_MODULAR, 
                model_kwargs = {"surrogate" : Surrogate(botorch_model_class=FixedNoiseGP, model_options={'train_Yvar': 0}), "botorch_acqf_class": qNoisyExpectedHypervolumeImprovement},
                num_trials=-1,  # No limitation on how many trials should be produced from this step
            ),
        ]
    )

**Comment by esantorella** [comment]
> hi，@esantorella，thanks for you relaying。The user_level_data you mentioned above is the relative difference from control group and experiment group with different observed time windows？

Good point, yes! I edited the code snippet above to make this more clear. Generally in an A/B test, one should difference against a control group to remove variation over time. So the mean is the difference in means between test and control, and the "sem" (standard error of the mean) is the standard error of that difference.

**Comment by esantorella** [comment]
> hi，@esantorella, I use service API, i do not know how to set the train_Yvar with FixedNoiseGP

You actually don't need to specify that you need to use `FixedNoiseGP` and `qNoisyExpectedHypervolumeImprovement`; Ax is smart enough to figure that out on its own. So something like this should work:

```python
gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.SOBOL,
            num_trials=10,
            min_trials_observed=10,
            max_parallelism=10,
            model_kwargs={"seed": 999},
            model_gen_kwargs={},
        ),
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            # model_kwargs = {"surrogate" : Surrogate(botorch_model_class=FixedNoiseGP, model_options={'train_Yvar': 0}), "botorch_acqf_class": qNoisyExpectedHypervolumeImprovement},
            num_trials=-1, # No limitation on how many trials should be produced from this step
        ),
    ]
)

ax_client = AxClient(generation_strategy=gs)
```

That being said, you may not even need to specify a `GenerationStrategy` at all; you may be using a more complicated API than necessary. Take a look at the [Service API Tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html). If you just do `ax_client = AxClient()` and then start the optimization loop, Ax will figure out that a `FixedNoiseGP` is appropriate (because you passed in an `sem` value) and that `qNoisyExpectedHypervolumeImprovement` is appropriate (because you have multiple metrics). What you would lose from that simpler API is the ability to specify how the SOBOL initialization trials are generated.

**Comment by cyrilmyself** [comment]
Hi，@esantorella ，thank you for your timely response.  I really appericate it.
