### ISSUE TITLE
how to use Banit Optimization of AX if i want to set multiple objects?

### ISSUE THREAD

**Issue by cyrilmyself** [facebook/Ax#2010]
https://ax.dev/tutorials/factorial.html
In above tutorials，there is only one object used；
I need to consider multiple objects, but i do not know how to set multiple objects in MAB. Could someone help me?

**Comment by bernardbeckerman** [comment]
@cyrilmyself I believe the first step would be to use a MultiObjectiveOptimizationConfig per [this tutorial](https://ax.dev/tutorials/multiobjective_optimization.html), though I'm not sure the Thompson model from the tutorial you linked is compatible with this. Might it be possible to follow the MultiObjectiveOptimization tutorial instead of the one you linked? cc @sdaulton who is our Modeling and Optimization oncall.

**Comment by sdaulton** [comment]
Yea, that's right. Currently, empirical Bayes Thompson sampling is not supported with multiple objectives. I'd recommend using the multi-objective Bayesian optimization tutorial that @bernardbeckerman linked to.

**Comment by cyrilmyself** [comment]
@bernardbeckerman @sdaulton thank you for your all replying, it really helps me a lot

**Comment by bernardbeckerman** [comment]
Sure thing! Closing this out : )
