### ISSUE TITLE
[Question] recommended approaches to non-stationarity

### ISSUE THREAD

**Issue by dharris10-chwy** [facebook/Ax#212]
Hi, I just wanted to start by saying that I'm really excited about this project and have appreciated being able to read @lena-kashtelyan's and @Balandat's helpful replies to other questions here.

I'm thinking about running an experiment where I expect strong time-of-day and day-of-week effects, and I was wondering about the best approach to take. Is there a way to add covariates describing each Batch Trial (for example, specifying that it occurred on a weekend)? I've been looking at the documentation for `batch_trial`, but I wasn't able to identify anything about how batch/trial effects are normally handled.

Thanks in advance for your time!

**Comment by 2timesjay** [comment]
@dharris10-chwy We're happy you like the project. 

In general, we don't explicitly address periodic effects. The closest that we have is the batchTrial-based design for Field Experiments. An experiment with multiple batchTrials at different times is designed to handle arbitrary drift in experiment metrics over time so that the best arms can still be identified correctly even if there is some seasonal or weekly effect between trials. 

https://ax.dev/tutorials/factorial.html

So if metric drift is fairly consistent for each arm, you won't need to take any extra steps.

Where this won't help you as much is if you expect the results to radically change over time. E.g. Arm 1 performs best during the day and Arm 2 performs best at night. In that case you might consider a time series approach that specifically integrates periodic information at different frequencies, for instance: https://facebook.github.io/prophet/

Tagging @bletham and @Balandat  for additional input.

**Comment by 2timesjay** [comment]
Feel free to reopen if you have additional questions.
