### ISSUE TITLE
Duplicate arms (parameter values) for discrete applications

### ISSUE THREAD

**Issue by winf-hsos** [facebook/Ax#230]
I am using the service API and I have a problem with 3 discrete parameters. When running the loop, I always get a series of identical arms, and it takes a while until I get different suggestions (if I even get them). 

I tried the same with continuous parameters, and here I can see that in fact the values change, but only in the second or third decimal place. It looks like BO is exploiting a local minimum (the values are far from optimal at this point). So I guess BO thinks it's making a new suggestion, but as the parameters are defined as discrete and therefore rounded to the next integer, the suggestion is not new after all. 

How can I make sure that I don't get duplicate suggestions for experiments with only discrete parameters?

Thx 
Nicolas

**Comment by lena-kashtelyan** [comment]
@winf-hsos, your hunch is exactly right, the issue originates in the rounding of values suggested in continuous space. Someone from the team will be back to you with a suggested solution; for now, you can use Sobol generation strategy for you optimization via one of the following two ways (I presume you are using the Service API, since I saw you discuss example code from it on another issue –– correct me if I'm wrong):
1. `choose_generation_strategy_kwargs` way, during experiment creation:
```
ax_client.create_experiment(
    ....,
    choose_generation_strategy_kwargs={"no_bayesian_optimization": True}, 
)
```
2. Passing generation strategy during the initialization of `AxClient`:
```
from ax.modelbridge.generation_strategy import GenerationStrategy, GenerationStep
from ax.modelbridge.registry import Models
sobol_gs = GenerationStrategy(steps=[GenerationStep(Models.SOBOL, num_arms=-1)])
ax_client = AxClient(...,  generation_strategy=sobol_gs)
```

**Comment by lena-kashtelyan** [comment]
I'm going to close this and move the discussion to #228!
