### ISSUE TITLE
switch from qNEHVI to another qNParEGO

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2473]
is qNEHVI the defualt algorithm? and how can we switch to qNParEGO? are we still able to get better resullt even we do not know the interssting  region (we have no information abou the thershold value of the objective functions). Anthor question how can we choose the the number of iteration ? should we start by 100 iterations and check the results  in case MOO?

**Comment by saitcakmak** [comment]
Hi @Fa20. We use qLogNEHVI by default for MOO (https://arxiv.org/abs/2310.20708), which is qNEHVI that leverages more stable computations for better optimization performance. 

> how can we switch to qNParEGO?

We currently don't have a ParEGO model in OSS Ax. If you were to implement a BoTorch acquisition function for ParEGO, you can utilize it with the Modular BoTorch Model setup: https://botorch.org/tutorials/custom_acquisition. We do plan to expose ParEGO later this year.

> are we still able to get better resullt even we do not know the interssting region

Whether one algorithm or the other works better is generally problem dependent. If you don't know the interesting region, NEHVI will utilize the nadir point as the reference point, which will lead to it trying to discover the full Pareto frontier. ParEGO, depending on the implementation, will try to do a very similar thing. We generally recommend NEHVI for 2-3 objectives and switch to ParEGO for >4 objectives due to computational reasons.

> Anthor question how can we choose the the number of iteration ? should we start by 100 iterations and check the results in case MOO?

This is again problem dependent. In practice, we'd pick the number of iterations based on experience with similar problems. 100 iterations should be plenty for BO for most problems to get to a practical optima.

**Comment by Fa20** [comment]
thanks for your answer
