### ISSUE TITLE
Using a trained prediction model as observations

### ISSUE THREAD

**Issue by Abrikosoff** [facebook/Ax#2494]
Dear Ax Team,

This is more of a conceptual question rather than a technical one, so I'm hoping it would still kind of fit here. I am doing a basic DoE workflow with Ax; generating experimental suggestions is not a problem, but getting observations corresponding to those experiments is rather costly, and hence I would like to make sure that my model is relatively good before performing the suggested experiments. So I would need a model that gives me "simulated" experimental observations (in order for me to be able to continue the suggestion-observation cycle). Right now I am using another trained model (using some pre-existing data) to predict the observations, but this would mean that my DoE results will be dependent on the quality of this trained model. But I know for sure that the quality of this model is not as good as I expect it to be.

How would one proceed in this situation? I'm not even sure if what I am suggesting is a good way to proceed, so any and all suggestions would be really welcome!

Edit: I am thinking of returning the (trained) model predictions as well as prediction error to the Ax client, but I'm not sure whether this would help improve the quality of the Ax model.

**Comment by sdaulton** [comment]
I find it helpful to perform leave-one-out cross-validation and plot the predicted metrics vs actual metrics and analyze model diagnostics. In your scenario, you can pass the model prediction and prediction error (if known to AxClient) and then evaluate the GP model fit in Ax. You may want to try just passing NaN instead of the prediction error to let Ax infer the noise level. Does that answer your question?

Here is some example code to do this when using AxClient:

```
from ax.modelbridge.cross_validation import cross_validate
from ax.plot.diagnostic import tile_cross_validation
from ax.utils.notebook.plotting import render

model = ax_client.generation_strategy._curr._fitted_model
cv = cross_validate(model)
render(tile_cross_validation(cv))
```

**Comment by mgarrard** [comment]
closing this issue, please re-open if additional help is needed :)
