### ISSUE TITLE
Last trial not being recognized (in the submitit tutorial)

### ISSUE THREAD

**Issue by StevePny** [facebook/Ax#2523]
This issue may be related to #2221 @mgarrard. I noticed the same issue but it is not related to the plotting. With the [submitit tutorial](https://ax.dev/versions/latest/tutorials/submitit.html):

If I [add a manual job](https://github.com/facebook/Ax/issues/2506#issuecomment-2169017272) that has decent performance and then run until the first BoTorch sample, for example:
```
# SGP added: test attached trials
params_baseline, trial_index_baseline = ax_client.attach_trial(parameters={"x": 0.0, 
                                                                           "y": 0.0})
```

and then run with:
```
total_budget = 7
num_parallel_jobs = 1
```
I get:
 
<img width="584" alt="Screen Shot 2024-06-14 at 7 14 42 PM" src="https://github.com/facebook/Ax/assets/11303168/bedf37bd-1fbe-49a8-a7f5-5fdd8d7ddb59">

**The last trial should be the best result, but it is not registered at all. If I run the optimization one more step, that result appears but then the new last one does not.**

For our case, the experiments are extremely expensive, so missing out on the results from the last trial is a big loss.

Incidentally, why is the result metric reported at `25.0000` in the realtime feedback display but shows up as `24.85217814794948` at the end of the optimization?

**Comment by bernardbeckerman** [comment]
Taking a look!

**Comment by bernardbeckerman** [comment]
@StevePny please add the following line before calling ax_client.get_best_parameters:

```
ax_client.generation_strategy._fit_current_model(data=ax_client.experiment.lookup_data())
```

This will retrain the model, which will add all the latest points to the training data, from which the best_point is selected. I'll work on getting this added to the tutorial, or better yet to get_best_parameters or somewhere else under the hood. Thanks for alerting us to this issue!

> Incidentally, why is the result metric reported at 25.0000 in the realtime feedback display but shows up as 24.85217814794948 at the end of the optimization?

This is because Ax uses the modeled value rather than the observed value, which can provide improved accuracy by leveraging nearby data. To use the raw values to choose your best trial instead, call get_best_parameters with `use_model_predictions=False`. Alternatively, if you know the noise level of your observations, you can make the outputs of the evaluate function be tuples of `(mean, sem)`, e.g., substituting the last line of `evaluate` with

```
    return {"result": ((x - 3)**2 + (y - 4)**2, 0.0)}
```

would indicate to Ax that the observations are exact and noiseless.

Hope that helps!

**Comment by bernardbeckerman** [comment]
Closing this out but please feel free to comment/reopen if you need further assistance here.
