### ISSUE TITLE
Tutorial uses unknown attribute

### ISSUE THREAD

**Issue by wooohoooo** [facebook/Ax#255]
Hi, 

the tutorial found here https://ax.dev/tutorials/factorial.html uses an unknown attribute, 'reweight_status_quo' of 'BatchTrial'. The error is shown below. 

AttributeError: 'BatchTrial' object has no attribute 'reweight_status_quo'

**Comment by lena-kashtelyan** [comment]
Hi, @wooohoooo! What an excellent username you've got : ) 

An outdated version of the tutorial got shipped with the most recent stable version of Ax (0.1.9), but we have fixed the tutorial since, so the version of the tutorial on latest (aka master, website version for which is built nightly) works: https://ax.dev/versions/latest/tutorials/factorial.html. 

In case you want to view something else on the latest rather than stable version of the website: to switch between versions, you can click the version name link in the top right corner.

**Comment by lena-kashtelyan** [comment]
Keeping this issue open until the new stable version with fixed tutorial is released.

**Comment by wooohoooo** [comment]
Hi @lena-kashtelyan, thanks for the response. New tutorial works well. Looking forward to the new release!

**Comment by Jakepodell** [comment]
fix landed in new release
