### ISSUE TITLE
How to set discrete parameter range?

### ISSUE THREAD

**Issue by JanoschMenke** [facebook/Ax#256]
Maybe a stupid question but how would I set up a discrete parameter range for example the size of a hidden layer. Like in the format for the learning rate, but for discrete values?
`{"name": "lr", "type": "range", "bounds": [0.0002, 0.01], "log_scale": True}`

**Comment by sdsingh** [comment]
For discrete parameter ranges, you have two options. Specifying the values as ints, rather than floats, will make the creation API Inter your parameters as int values.

To be explicit, you can also set “value_type” to “int” in your dictionary above. You can see more details in our service tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html
