### ISSUE TITLE
[Question] Can I change acquisition function and kernel in service API?

### ISSUE THREAD

**Issue by rinc5** [facebook/Ax#278]
I appreciate your fantastic jobs and kind supports.

Can I change acquisition function (e.g. PI, MI, UCB) and kernel (e.g. RBF, Squared Exponential) in service API?

About changing acquisition function, it's mentioned at lena's second comment in #120 but the tutorial's link doesn't work.
And I worry about whether I can change  acquisition function because BoTorch's document (https://botorch.org/api/acquisition.html) says many acquisition functions are for single-outcome.

My use case is the same as #273:
* 2 outcomes and 3 parameters
* Using external data
* Parameter constraint and outcome constraint

Thank you in advance for any kind of help.

**Comment by lena-kashtelyan** [comment]
Hi, @rinc5! Sorry about that dysfunctional link –– the benchmarking tutorial has been temporarily removed as the Ax benchmarking suite underwent a few major changes –– the new tutorial will be up once the changes are finalized. Luckily, we should not need that tutorial for your question. 

To change acquisition function in the Service API, you will need to make your own [generation strategy](https://ax.dev/api/modelbridge.html#module-ax.modelbridge.generation_strategy). You can use [this comment](https://github.com/facebook/Ax/issues/199#issuecomment-551884560) or the [`choose_generation_strategy`](https://github.com/facebook/Ax/blob/master/ax/modelbridge/dispatch_utils.py#L115) function as an example of how a generation strategy is constructed. 

In your generation strategy, you will want to set a custom `BotorchModel` as the second model after Sobol (instead of `Models.GPEI` in the comment I linked above and in `choose_generation_strategy`). [BoTorch tutorial](https://botorch.org/tutorials/custom_botorch_model_in_ax) on using a custom BoTorch model in Ax will help you set up the model with custom acquisition function (please follow up in this issue if help is needed to get that working, @Balandat or @danielrjiang can help). 

If you do not need to save your experiment to JSON or a database, you can just do `GenerationStep(model=get_botorch, ...)` as your second generation strategy step (`get_botorch` here is the same as the one in the custom BoTorch + Ax tutorial above). If you do need storage, let me know, and I can walk you through the setup that will allow for storage. 

Does all this make sense?

**Comment by rinc5** [comment]
Thank you for your quick reply, @lena-kashtelyan , @Balandat !
I'll try your recommended pages. It may take a while because of my lack of skill. I'll let you know if I have any questions.

**Comment by lena-kashtelyan** [comment]
Closing this for now, but feel free to reopen or create a new issue if you have follow-up questions, @rinc5 !

**Comment by rinc5** [comment]
Sorry for taking long time.
I have two follow-up questions.

1. Why is `GenerationStep(model=Models.SOBOL, ...)` needed?
Is it for generating initial points? I only use `GenerationStep(model=Models.GPEI, ...)` in my current code. But should I add `GenerationStep(model=Models.SOBOL, ...)` as the first step?

2.  How do I pass factory functions to `get_botorch`?
I understood that I can use BoTorch with Ax by setting factory functions (e.g. [`_get_and_fit_simple_custom_gp`](https://botorch.org/tutorials/custom_botorch_model_in_ax#Define-a-factory-function-to-be-used-with-Ax's-BotorchModel) for custom GP model and [`get_scalarized_UCB`](https://botorch.org/tutorials/custom_acquisition#Ad-hoc-testing-Scalarized-UCB) for custom acquisition function) to `get_botorch`'s argument `model_constructor` and `acqf_constructor` respectively. @lena-kashtelyan told me I can use `GenerationStep(model=get_botorch, ...)`. It is very simple but I don't know how to pass my factory functions to BoTorch.

Maybe I misunderstood, so any advice would be greatly appreciated.
