### ISSUE TITLE
"Contour" plot when optimizing 1 hyperparameter

### ISSUE THREAD

**Issue by KevinMusgrave** [facebook/Ax#315]
Is there a way to get a "contour" plot but for the case when you're optimizing just 1 hyperparameter? Something like this figure from the BayesianOptimization package:

![image](https://user-images.githubusercontent.com/2314891/81486825-9afdf000-9225-11ea-930d-f89e43aa9f28.png)

**Comment by ldworkin** [comment]
Hi @KevinMusgrave -- absolutely! I imagine you're looking for a slice plot: https://ax.dev/tutorials/visualizations.html#5.-Slice-plots

Let me know if that helps! (Ooc, did you not see that in the tutorial because it was farther down in the page from the contour plot? It should probably be right below/above it ...)

**Comment by KevinMusgrave** [comment]
Ah my bad, I'm not sure why I missed that. Thanks!
