### ISSUE TITLE
[Question] What's the difference between mark_failed and  mark_abandoned a trial ?

### ISSUE THREAD

**Issue by bitosky** [facebook/Ax#329]
What's the difference between `mark_failed` and  `mark_abandoned` a trial ?
I'm going to use on of them when I get an awful result, but I don't know the difference between them.

**Comment by lena-kashtelyan** [comment]
Hi, @bitosky! Here are our API docs on trial statuses: https://ax.dev/api/core.html#ax.core.base_trial.TrialStatus and a relevant section in our docs: https://ax.dev/docs/core.html#experiment-lifecycle. 

In practice, a parameterization in an abandoned trial may never be re-suggested by our models (as we assume the user-made decision to abandon the trial was made for a reason), while a parameterization from a failed trial may be re-suggested (since we take a 'failure' to mean a machine failure during trial evaluation). Does that help?

**Comment by bitosky** [comment]
@lena-kashtelyan Thank you for answering my question. I think I should try `mark_abandoned`.
