### ISSUE TITLE
[Question] offline logged data, noisy evaluation, sticky decisions

### ISSUE THREAD

**Issue by hanan-vian** [facebook/Ax#330]
Thanks for releasing Ax, it seems like a useful platform.
- How can I warm-start a model with offline data which was already collected so I don't need to experiment from scratch, e.g. I have logged data in the form of time, parameters, outcome (which might be noisy).
- This leads me to the next questions: does Ax supports noisy outcomes? I mean the case where the function return is stochastic. 
- Last but not least, can I enforce stickiness in settings so that the system does not go wild but sample the same settings for a while before trying something new (maybe introduce a cost of changing settings?)

**Comment by hanan-vian** [comment]
@lena-kashtelyan

**Comment by 2timesjay** [comment]
@hanan-vian 

1) If you have known data with outcomes, you can use https://ax.dev/api/service.html#ax.service.ax_client.AxClient.attach_trial to add trials and "complete_trial" to add resulting outcomes. 

In general you can also save and load experiments in JSON or relational dbs. https://ax.dev/tutorials/gpei_hartmann_service.html#7.-Save-/-reload-optimization-to-JSON-/-SQL

2) If your data is noisy with known variance you can specify that. If noise is unspecified then by default we will use a version of GPEI that infers the level of noise.  The only time we treat it as noiseless is when you specify it as 0. Outcomes are returned as (mean, sd) tuples as in https://ax.dev/tutorials/gpei_hartmann_service.html#3.-Define-how-to-evaluate-trials (the example has 0 noise, set it to None for unknown noise).

3) Please give more details about what you want. I don't think we directly do what you want, but the standard algorithm will sample points based on a criteria called "Expected Improvement" which will revisit points based on a combination of remaining model uncertainty and expected outcomes, so eventually uncertainty will be quite low at the best point the algorithm finds as well as around all similar-quality local maxima because it will revisit them.

If this doesn't achieve what you're hoping for let us know.

**Comment by hanan-vian** [comment]
I would like to use Ax.dev to optimize an online system (see https://research.fb.com/blog/2018/09/efficient-tuning-of-online-systems-using-bayesian-optimization/). 
I would like to use offline data (1), at every setting the performance is stochastic, thus several samples are needed to estimate the real performance (2). Moreover, there is some cost in trying to change the settings at every time tick, thus I would like to impose some commitment to decisions, aka staying in the same settings for a while before switching (3). 
I guess I am looking for a "safe" BO which only looks at near settings. Maybe something like https://safeopt.readthedocs.io/en/latest/

**Comment by 2timesjay** [comment]
@hanan-vian I'll give my best guess at answers, though I'll need more context in some cases.

(1) To use a surrogate source of information like simulated offline data to help you better run online experiments, follow our Multi-type optimization tutorial: https://ax.dev/tutorials/multi_task.html

(2) To reduce variance the best option is to make each trial you run actually dispatch multiple tests and aggregate them yourself. We'd like to be able to handle this for you, but we don't implement it right now and adding duplicate identical arms in the same batch can cause numerical errors in model fitting.

(3) We don't support anything like safeopt. You could try rejecting candidates and generating new ones until you get a "Safe" point based on some heuristic, but you might end up in situations where we repeatedly generate "unsafe" points indefinitely. Our best bayesopt methods (Gaussian Processes with Expected Improvement) have the property that when multiple local optima are being explored candidates will tend to be distributed between those local optima. Towards the end of optimization, however, points will tend to cluster around the true optima.

**Comment by 2timesjay** [comment]
Closing pending further follow-ups.
