### ISSUE TITLE
[Question]: How to convert an array to an arm that would be the initial set? 

### ISSUE THREAD

**Issue by rima2992** [facebook/Ax#344]
Hi, 
ich want to fix the initial training set ([a,b,c ...]) and give it as a the first batch trial to the experiment. I would appreciate it if someone showed me how to do it.

**Comment by lena-kashtelyan** [comment]
Hi, @rima2992! Which API are you using? It's instrumental for me to know that so I can help you figure out how to set the initial trial. 

Can you also tell me a bit more about your experiment? Since you are using batch trials, I'm assuming you are running an adaptive A/B testing experiment? Do you have data for the initial set of parameter configurations you'd like to convert to arms?

**Comment by lena-kashtelyan** [comment]
@rima2992, assuming you found the answer and closing the issue –– let us know if you still need help and feel free to reopen if so!
