### ISSUE TITLE
missing 1 required positional argument: 'standard_bridge_kwargs'

### ISSUE THREAD

**Issue by microprediction** [facebook/Ax#392]
When running the example on the homepage

**Comment by lena-kashtelyan** [comment]
@microprediction, please post the exact code snippet you ran and the stack trace for the error that you got –– it's difficult to debug based on the information you gave.

**Comment by microprediction** [comment]
Lena, 
 
    Code is at 
https://github.com/microprediction/tuneup/blob/master/tests/test_ax.py
 
    I notice issue 
https://github.com/facebook/Ax/issues/237 is similar
 
Peter

**Comment by lena-kashtelyan** [comment]
@microprediction, the exception you show in the notebook appears different from the one in the title of this issue. The new exception you show was brought up in #387 –– the issue was with a faulty version we released earlier today. Updating to 0.1.16 should fix it. Feel free to reopen this or create a new issue if something is still not working!

**Comment by microprediction** [comment]
Thanks for the speedy response.  Do you plan to release 0.1.16 to PYPI?  Currently the broken one is there.
