### ISSUE TITLE
Installation fails on Windows 

### ISSUE THREAD

**Issue by aliosmanulusoy** [facebook/Ax#405]
I followed the docs to install Ax and ran `pip3 install ax-platform` on Windows. I get the following error:

```
ERROR: Could not find a version that satisfies the requirement torch>=1.6 (from botorch>=0.3.1->ax-platform) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.6 (from botorch>=0.3.1->ax-platform)
```

**Comment by 2timesjay** [comment]
@aliosmanulusoy are you able to use Conda? I've recently installed ax-platform and all its dependencies using conda on Windows.

Botorch has further instuctions here: https://github.com/pytorch/botorch#installation 

Pytorch also suggests using Conda, and it looks like PyPi has not updated from 1.2 while I know that conda-forge has the most recent version: https://anaconda.org/pytorch/pytorch

**Comment by Balandat** [comment]
The issue is that the windows binaries for pytorch are too big for PyPi, so you have to provide a mirror to pip. For torch that is (see the "getting started" instructions on the pytorch website): `pip install torch -f https://download.pytorch.org/whl/torch_stable.html`. After doing that the pip install should work.

We should probably find a way to automatically do that in the botorch setup, just need to figure out how to provide that mirror.

**Comment by aliosmanulusoy** [comment]
Thanks @Balandat. Your suggestion worked for me.
