### ISSUE TITLE
[Ray] Integration with RayTune still has some issues: "NotImplementedError: RandomModelBridge does not support prediction." error

### ISSUE THREAD

**Issue by rogertrullo** [facebook/Ax#423]
Hi, I am having the same issues as @ilcord in #345
I am doing something like this:

`step1=GenerationStep(Models.GPEI, num_trials=-1, min_trials_observed=0, max_parallelism=None, use_update=False, enforce_num_trials=True, model_kwargs=None, model_gen_kwargs=None, index=0)`

`strategy=GenerationStrategy([step1])`
`ax = AxClient(generation_strategy=strategy, enforce_sequential_optimization=False)`
which gives this strategy:
`GenerationStrategy(name='GPEI', steps=[GPEI for all trials])`
but then I run 
`tune.run(...)`
and I get this error:
`StandardizeY transform requires non-empty observation data.
`
Even when using the default setting 
`GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 1 trials, GPEI for subsequent trials])
`
if I don't call tun.run twice I have the following error:
`NotImplementedError: RandomModelBridge does not support prediction.
`Looks like it stays in Sobol and it doesnt change to the GP model ?

**Comment by sdsingh** [comment]
Hi @rogertrullo! Sorry you're still experiencing this. As a first check, are you on the updated version of Ax mentioned in the original issue, 0.1.18?

**Comment by rogertrullo** [comment]
Thanks @sdsingh yes I’m using the latest version.

**Comment by lena-kashtelyan** [comment]
@rogertrullo, is `tune.run` in your case set up exactly like this: https://ax.dev/tutorials/raytune_pytorch_cnn.html#4.-Run-optimization? Changing `search_alg=AxSearch(ax)` to `search_alg=AxSearch(ax_client=ax, max_concurrent=3)` is crucial there, since it's the `max_concurrent` setting that prevents Ray from running all trials concurrently, which results in use of Sobol engine (with `RandomModelBridge`) for generation of all trials and prevents GPEI model (with `TorchModelBridge`, which will support prediction) from ever kicking in.

**Comment by rogertrullo** [comment]
Thanks @lena-kashtelyan I was missing that!
so just to clarify, does it mean that if I set Sobol `num_trials=5` for example, and I set `max_concurrent=10` it will first perform the 10 parallel trials before moving to next generation strategy?

**Comment by lena-kashtelyan** [comment]
@rogertrullo, that's right –– for the first batch of trials deployed in parallel, it will generate the maximum of `num_trials` in Sobol step and `max_concurrent` trials from Sobol. Since those trials are all generated at once and deployed concurrently, there is no data available during that generation, so the Bayesian optimization phase simply can't kick in until the first batch of `max_concurrent` trials is completed and their data is available. To avoid confusion, I'd just set `num_trials` for Sobol and `max_concurrent` to the same value (or have the former be the latter * some N, if you want more than one concurrent batch to be from Sobol).

**Comment by lena-kashtelyan** [comment]
Closing the issue since it seems we answered the question; feel free to reopen if you have follow-ups, @rogertrullo!
