### ISSUE TITLE
Question: ALEBO feature importance

### ISSUE THREAD

**Issue by Pzmijewski** [facebook/Ax#426]
Hello,
is it possible to get the feature importance in ALEBO?

I know its works in normal Ax by using functions like:
`ax.plot.feature_importances.plot_feature_importance_by_feature(model)`

If i do it in ALEBO it get:
`torch.nn.modules.module.ModuleAttributeError: 'ModelListGP' object has no attribute 'covar_module'`

thanks

Philipp

**Comment by lena-kashtelyan** [comment]
cc @bletham, who knows ALEBO best!

**Comment by bletham** [comment]
Not really, we should probably have this throw a better error :-)

Feature importance in a GP is usually measured by looking at the ARD lengthscales for each parameter. With ALEBO the GP is fit only in the embedding, and then the metric is the Mahalanobis metric instead of the ARD metric. But we don't really care about feature importance within the embedding, we are interested in feature importance in the original, high-dimensional space. So we have to somehow convert the measure of feature importance from the embedding to the high-dimensional space.

Each parameter in the high-dimensional space is a linear combination of embedding parameters. For high-dimensional parameters x = [x_1, ..., x_D] and embedding parameters y = [y_1, ..., y_d], we have that
```
x = Binv y
```
where Binv is the upwards projection matrix (the pseudo-inverse of the downwards projection matrix B). So,
```
x_i = \sum{j=1}^d Binv_{i, j} y_j.
```
So given a feature importance measure for each feature in the embedding `y`, we would have to figure out a meaningful way of combining those according to `Binv_{i, :}` to get a feature importance for x_i. I'm not sure what related work there is in this space or if there is a clear right thing to do.

That said, my experience in practice with using ALEBO is that people are usually very interested in feature importance, and it has been one of the first things people that I've worked with on high-dimensional optimizations have asked about. Since I haven't yet given enough thought to the above question about how to convert embedding feature importance to meaningful high-dimensional feature importance, for now I've been doing something a bit easier: I just fit a separate RandomForest model in the high-dimensional space and then measure feature importance directly on that model. RandomForest usually fits pretty well in high dimensions, and has well understood techniques for computing feature importance. It can also be done directly in Ax. This is the code that I use, assuming `exp` is the Ax Experiment object and `data` is the Ax Data object.

```Python
from ax.utils.notebook.plotting import render, init_notebook_plotting
from ax.plot.diagnostic import interact_cross_validation
from ax.modelbridge.cross_validation import cross_validate

from ax.modelbridge.numpy import NumpyModelBridge
from ax.models.numpy.randomforest import RandomForest
from ax.modelbridge.transforms.unit_x import UnitX
from ax.modelbridge.transforms.standardize_y import StandardizeY

from matplotlib import pyplot as plt
import numpy as np

init_notebook_plotting()

D = 30  # whatever the number of parameters in the high-dimensional space is

# Fit an RF
m = NumpyModelBridge(
    search_space=exp.search_space,
    model=RandomForest(),
    transforms=[UnitX, StandardizeY],
    experiment=exp,
    data=data,
)

# Check that model cross validation is OK, so that the feature importance can be trusted
cv = cross_validate(m)
render(interact_cross_validation(cv))

# Pull feature importances off of the fitted sklearn random forests
imps = {
    metric: m.model.models[i].feature_importances_
    for i, metric in enumerate(m.outcomes)
}

# Plot all feature importances, with feature sorted by importance
for metric in imps.keys():
    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_subplot(111)
    z = imps[metric]
    idx = z.argsort()
    ax.scatter(x=z[idx], y=np.arange(D), marker='x', s=100)
    ax.set_yticks(np.arange(D))
    labels = np.array(m.parameters)

    ax.set_yticklabels(labels[idx], fontsize=14)
    ax.set_title(metric, fontsize=20)
    ax.set_xlabel('Feature importance', fontsize=14)
    ax.grid(alpha=0.2);
```

So far this has seemed to provide something reasonable. Though there is an important caveat: the embedding induces confounding in the search space. Because the high-dimensional parameters are computed as linear combinations of a much smaller number of embedding parameters, there will be some features in the high-dimensional space whose values are correlated. Correlation in the feature values means that there may be parameters that are measured as having low feature importance because they are correlated with a parameter that has higher feature importance, and so all of the importance is attributed to that other parameter. In short, I think that if feature importance as measured this way is high then it probably really is high; if it is measured as low, then it could be low or it could also just be confounded with a parameter that has high importance. Fortunately that confounding would be easy to verify by measuring the correlation between the feature values; but if a particular feature is confounded by a high-importance feature, then there really won't be any way to assess its individual importance. I hope that made sense.

**Comment by lena-kashtelyan** [comment]
Will close this for now, as it seems that it was answered as best it can be by @bletham, and there is no plan to support this functionality in Ax currently.
