### ISSUE TITLE
Using Service API to log previous trials

### ISSUE THREAD

**Issue by crrivero** [facebook/Ax#430]
I find the framework very useful, thanks! I am using it to select the best hyperparameter values for a set of machine learning models. In my setting, I am using the Service API since it takes a while to compute the actual output. Once I have the results, I report them back to the client. In some cases, I have data collected previously that I would like to consider in the experiment. I am using 'attach_trial' to inform a new trial (https://github.com/facebook/Ax/issues/197). However, it is not working as expected since I am not able to see the trials, please, find my script attached ([ax_step.txt](https://github.com/facebook/Ax/files/5550215/ax_step.txt)). It is creating multiple trials for data I have collected before but it seems the trials are not reflected in the client, for instance, I cannot access them from the generation_strategy or there are no best parameters. Thanks for the help!

**Comment by lena-kashtelyan** [comment]
Hi, @crrivero! You are doing everything correctly in terms of attaching trials and completing them and it is actually working as expected : ) 

> I am not able to see the trials

I imagine you are referring to the fact that the trials are not appearing in `ax_client.generation_strategy.trials_as_df`, correct? That is expected in this case, since those are the trials that belong to the generation strategy on your experiment, so trials produced in the course of that experiment by the Ax models. The trials you attach do not meet that definition, so they are not part of the generation strategy. Does that make sense? You can still view them in many ways; for example, via `ax_client.experiment.trials`. Let me know if the trials don't appear there, since in that case something is definitely going wrong.

>  there are no best parameters

This part might be a bug. Would you mind checking what happens if you do the following:

```
from ax.service.utils import get_best_raw_objective_point, get_best_parameters

best_raw_objective_point = get_best_raw_objective_point(ax_client.experiment)

best_overall = get_best_parameters(ax_client.experiment)
```
Specifically, I'm curious about the values of `best_raw_objective_point` and `best_overall` (or the errors you get while trying to retrieve those.

**Comment by crrivero** [comment]
Hi, @lena-kashtelyan. Thanks for your prompt answer! I am actually able to see the best parameters using the three functions (ax_client.get_best_parameters() and the ones you suggested). The same values are reported in all cases. However, if I have trials attached to a certain generation strategy and I attach these trials, the ones I manually attached are not considered.

It makes sense that the trials do not appear in ax_client.generation_strategy.trials_as_df, and that was exactly my point. A follow-up question that I have is whether I can attach the trials to the generation strategy then. My use case is that I want to recreate the same process as I did before with another AxClient. I have the parameters suggested by a previous client and results, so I would like to resume the process at the same stage as I was before but with a fresh AxClient. Is there a way like ax_client.generation_strategy.attach_trial in which I can provide parameters and obtained measurements?

Thanks!

**Comment by lena-kashtelyan** [comment]
>  if I have trials attached to a certain generation strategy and I attach these trials, the ones I manually attached are not considered.

That's interesting, let me look into it!

>  would like to resume the process at the same stage as I was before but with a fresh AxClient

We offer a way to just resume both the experiment and the generation strategy, would that work for you? If so, you can just do: `new_ax_client = AxClient.load_from_json_file()`, as shown in this section fo the tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html#7.-Save-/-reload-optimization-to-JSON-/-SQL. Let me know if that's not exactly what you were looking for.

**Comment by lena-kashtelyan** [comment]
@crrivero, I'll close this since I hope my answer above should've covered what you were looking for. Feel free to reopen and follow up if not!

It is strange still that getting best point from experiment with attached trials only did not work, and we'll definitely look into that, but that doesn't seem to be the main point of this issue, so seems fair to close.
