### ISSUE TITLE
saving MultiObjective Model -> JSONEncodeError

### ISSUE THREAD

**Issue by optiluca** [facebook/Ax#440]
I've made a simple demo script based on https://ax.dev/tutorials/multiobjective_optimization.html, which you can find here https://gist.github.com/optiluca/feea7e9c4c91dd84daf3885eca7378c1.   I've added a save step, which fails with:

ax.exceptions.storage.JSONEncodeError: Object OptimizationConfig(objective=MultiObjective(metric_names=['a', 'b'], minimize=False), outcome_constraints=[], objective_thresholds=[ObjectiveThreshold(a >= -18.0), ObjectiveThreshold(b >= -6.0)]) passed to `object_to_json` (of type <class 'ax.core.optimization_config.MultiObjectiveOptimizationConfig'>) is not registered with a corresponding encoder in ENCODER_REGISTRY.

How do I save a MultiObjective experiment to be able to look at results later and/or resume the optimisation?

**Comment by 2timesjay** [comment]
This is fixed in https://github.com/facebook/Ax/commit/ac2f7bbf7881cdf23ad466c88a5f7cd8db0f40b7#diff-c91239c574c9aeea90ec894c8e5612318015e877b5195ab36bf885f83147a03f

You can build from the most recent master version or patch in the fix yourself (we don't have a date for our next release but we will aim for sometime in the next 3 weeks).

You'll also need to register the metrics being saved with these lines:

```
from ax.storage.metric_registry import register_metric

register_metric(metric_cls=MetricA)
register_metric(metric_cls=MetricB)
```

Combined with the recent PR, this successfully saves the experiment.
