### ISSUE TITLE
Discrete examples in high-dim search space and service API

### ISSUE THREAD

**Issue by dong-tony** [facebook/Ax#459]
I am working on a chemistry problem where I have a database of ~40000 molecules that have ~50 continous descriptors each. I am trying to use BO to optimize a certain property of the molecules, which have to be evaluated externally through simulations (the service API seems great for this). I already have ~300 molecules that I know the property values of from prior simulations, and I wish to use these to initiate the BO.

I am kind of lost in between the documentations of BoTorch and Ax and would greatly appreciate some pointers to get started. Here are some things I'm currently stuck on:

*  reading #421 I should setup the search space as continuous and then I need to define a custom `acqf_optimizer` that evaluates all the discrete examples in the database - I'm not too sure how I should do this, and how to integrate with the service API after?
* how to let Ax know about the 300 molecules that I already have the results for?

I'm fairly new to this and would love any other suggestions for how to better solve my problem. Thanks in advance!

**Comment by eytan** [comment]
Hi Tony,

This sounds like a very interesting problem. If I understand your setup
correctly, you are performing some sort of expensive search process where
evaluating any given molecule is time intensive, and for each molecule you
measure some score. You’ve already computed these quantities for 300
molecules. You can cheaply evaluate your surrogate wrt 40k molecules, and
your idea is to do explore/exploit with the surrogate wrt each molecule
before evaluating the molecule.

Since the whole process is rather bespoke, I might recommend starting with
BoTorch.

Because your problem is fairly high dimensional and you are evaluating a
discrete points, you might want to use TuRBO-1 with Thompson sampling
(“ts”). https://botorch.org/tutorials/turbo_1

Since points in the search space eventually needs to be mapped to discrete
molecules, you probably can’t use the default acquisition function
optimizer. You might instead take some number of initial samples in your
design space (raw samples in turbo), and the use a nearest neighbor search
algorithm like FAISS
https://github.com/facebookresearch/faiss/wiki/Getting-started to find a
few molecules in the neighborhood of each search point. The faiss index
only needs to be computed once before the start of the loop.  This nearest
neighbor search should speed things up and also limit the number of joint
samples you need to take. The right place to insert the faiss search might
be right before the MaxPosteriorSampling code, so that you can instead
sample from the (possibly de-duped) 1-4 nearest neighbors of X_cand using
faiss.

Setting up the initial data in BoTorch should be straightforward. It’s just
a matter of starting your loop with your existing data. Be sure to
normalize all of your input data to be 0 mean unit variance for best
performance.

Once you get to a good spot we’d be happy to help with putting this all
into ax, but for now it sounds like you might want to start with something
lower level.

Do you have any papers that describe similar setups? This problem area is
new to me, so I’m just suggesting what I’d do if I encountered such a
problem after thinking about it for 5 min. I am sure there are more
sophisticated approaches out there.

Best,
E

**Comment by dong-tony** [comment]
Thank you so much for your suggestions!

> You can cheaply evaluate your surrogate wrt 40k molecules, and your idea is to do explore/exploit with the surrogate wrt each molecule before evaluating the molecule.

Yep! that's exactly it.

I will definitely try implementing your suggestions. In terms of similar setups in literature, there is a [fairly recent one](http://doi.org/10.1021/acs.chemmater.0c00768) and examining their [code](https://github.com/hieuadoan/QM-ActiveLearning-Paper/blob/master/BO-1400HBE.ipynb) it appears the way they optimized their acquisition function (EI) is to just evaluate it at every single point in the dataset and pick the maximum from that. They had 15 descriptors and was exploring a space of 100k+ molecules, but a difference is that they are only looking for a predetermined number of molecules (40) that fall within a desired range of property scores rather than a global maximum. Which to me seems like a relatively easier problem.

Other than just being slow, are there any other problems associated with their way of optimizing the AF? 

Thanks again!

**Comment by eytan** [comment]
You can definitely just evaluate all 40k points EI and pick the best.  There is nothing wrong with that, and should work well if it's fast enough for you.

Please keep us posted on how that works out. If your number of function evaluations is quite limited, you can also try out using a random embedding-based method like ALEBO (although @bletham would have to give you pointers on how to hook that up).

Best,
e

**Comment by dong-tony** [comment]
Just to learn some of the basics and test my code I was running some trial experiments on my initial 300 molecule set that I know the scores of. I first tried the standard method I saw in literature where I evaluate EI at every possible point i.e. `X_next_index=argmax(acq_values)` and this was done with the analytic EI (q=1). I was still doing this within the TuRBO-1 framework and just replaced the `optimize_acqf()` code block. Santiy-checked by comparing to random exploration and it worked pretty well! Yay! Although, I also tried doing the EI scheme independently, without TuRBO-1, and I get the exact same results, did I inadvertently delete a part of the framework or is it just because my q=1 and/or it is a small dataset? 

Either way, I do want to learn and experiment with batching enabled tomorrow, since doing the molecule simulations in batches would be most efficient (submitting multiple jobs at once to a computing cluster). 

- I took a brief look at the qEI today, and I couldn't really figure out how to write the custom 'optimization' code block for it (if I still choose to just evaluate every single point). Is it even possible to use qEI for my case?
- For using TS instead, does FAISS help replace the selection of X_cand (the perturbation mask part) to use for MaxPosteriorSampling or does it just replace all of it as a whole? Sorry, i'm still learning the fundamentals behind all this so I may not be able to make the connections immedietely. Would greatly appreciate if you could explain this part a bit more in detail.

Thanks!

**Comment by eytan** [comment]
I am pretty sure that it should be possible to use qEI in your case, but it will require some custom code.  In particular, you could fork `optimize_acqf` to just evaluate some pre-specified set of points, rather than use optimize over some initial set of parameters `batch_initial_conditions` via `gen_candidates_scipy()`.  I'll loop in some other folks who can share more ideas / maybe lend a hand.

Re: the FAISS, my suggestion was that you could use whatever method to generate a candidate point X, and FAISS will be able to find the "nearest molecule" (for the given feature space).  It would therefore be a step after selecting X_cand.

**Comment by lena-kashtelyan** [comment]
I'm closing this issue as inactive, please get back to us an reopen if you need more assistance, @dong-tony!
