### ISSUE TITLE
Making sure model.gen() generate designated number of arms

### ISSUE THREAD

**Issue by nwrim** [facebook/Ax#464]
Hi,

We are a group of social scientists trying to use Bayesian optimizations in our experiment. We came across this wonderful library a few days ago and are trying to see how we can use it for our experiment. While trying out some features, we came across a problem that when using models in `ax.modelbridge.factory`, the number of arms generated from .gen() is less than what we feed in. For example, when running the following code snippet, the `generator_run` only has 3 arms, even though we used .gen(10):

```
ax.modelbridge.factory.DEFAULT_EHVI_BATCH_LIMIT = 20
# search space set up
search_space = ax.SearchSpace(
    parameters=[ax.RangeParameter(name="X1", lower=0, upper=2, 
                                  parameter_type=ax.ParameterType.INT),
                ax.RangeParameter(name="X2", lower=0, upper=2, 
                                  parameter_type=ax.ParameterType.INT),
                ax.RangeParameter(name="X3", lower=0, upper=2, 
                                  parameter_type=ax.ParameterType.INT),
                ax.RangeParameter(name="X4", lower=0, upper=2, 
                                  parameter_type=ax.ParameterType.INT),
                ax.RangeParameter(name="X5", lower=0, upper=2, 
                                  parameter_type=ax.ParameterType.INT),
                ax.RangeParameter(name="X6", lower=1, upper=10, 
                                  parameter_type=ax.ParameterType.INT)],
)

# dummy runner
class MyRunner(ax.Runner):
    def run(self, trial):
        return {"name": str(trial.index)}

# optimziation configuration set up
optimization_config = ax.OptimizationConfig(
    objective = ax.Objective(
        metric = ax.Metric(name="score"), 
        minimize = False,
    ),
)

# initialize experiment
experiment = ax.Experiment(
    name="ax_pilot_simulation",
    search_space=search_space,
    optimization_config=optimization_config,
    runner=MyRunner(),
)

# 20 initial SOBOL points
sobol = ax.Models.SOBOL(search_space=experiment.search_space)
sobol_result = sobol.gen(20)
experiment.new_batch_trial(generator_run=sobol_result)
experiment.trials[0].run().mark_completed()

# use get_GPEI
m = ax.modelbridge.factory.get_GPEI(experiment=experiment, data=ax.Data(df))
generator_run = m.gen(10, model_gen_options={"max_parallelism_override": 20})
experiment.new_batch_trial(generator_run=generator_run)
```

When running `.gen()`, it raises 
```
C:\Users\user\Anaconda3\envs\BoTorch\lib\site-packages\gpytorch\utils\cholesky.py:46: NumericalWarning:

A not p.d., added jitter of 1.0e-08 to the diagonal
```

warnings 7 times, which I suspect is related to the fact that the method generated only 3 arms even though we fed in 10.

Is there a way we can force the `.gen()` method to create 10 arms in this case? We are in a situation where creating a new batch is much more costly than increasing the number of arms in a batch, so we would like to make sure that we are running at least 10 arms in a single batch (for more exploration, etc). We get similar behavior when we use `ax.modelbridge.factory.get_GPKG` or `ax.modelbridge.factory.get_GPMES` instead of `ax.modelbridge.factory.get_GPEI`. We tried increasing `ax.modelbridge.factory.DEFAULT_EHVI_BATCH_LIMIT` to up to 100, but this does not seem to affect the result.

I have also looked at the suggestion at #129, but in our case arms within a batch is not independent of each other (it is similar to A/B testing with 10 versions), so I thought that it might be better to use BatchTrial instead of Trial for our case.

Finally, here is the `df` used in the `m = ax.modelbridge.factory.get_GPEI(experiment=experiment, data=ax.Data(df))` line in the above code snippet in case the issue is with the data (also, we were not able to find much documentation for the "n" parameter, which we found in the human in the loop experiment tutorial, but we assumed that this parameter is the number of time we tested the arm, which has quite a bit of inherent noise - it will be great if you can point us to documentation where this is explained in more detail):

|    |   arm_name | metric_name   |      mean |      sem |   trial_index |   n |
|---:|-----------:|:--------------|----------:|---------:|--------------:|----:|
|  0 |        0_0 | score         |  1.45263  | 0.297816 |             0 |  10 |
|  1 |        0_1 | score         | 11.7041   | 0.482149 |             0 |  10 |
|  2 |        0_2 | score         | 11.6606   | 0.398025 |             0 |  10 |
|  3 |        0_3 | score         |  1.93861  | 0.303447 |             0 |  10 |
|  4 |        0_4 | score         |  8.01971  | 0.316499 |             0 |  10 |
|  5 |        0_5 | score         | 26.3663   | 0.594298 |             0 |  10 |
|  6 |        0_6 | score         |  2.81728  | 0.275964 |             0 |  10 |
|  7 |        0_7 | score         |  0.860655 | 0.284651 |             0 |  10 |
|  8 |        0_8 | score         | 27.9965   | 0.519118 |             0 |  10 |
|  9 |        0_9 | score         | 11.2966   | 0.353236 |             0 |  10 |
| 10 |       0_10 | score         | 12.9839   | 0.3441   |             0 |  10 |
| 11 |       0_11 | score         | 22.5899   | 0.294546 |             0 |  10 |
| 12 |       0_12 | score         | 10.185    | 0.506147 |             0 |  10 |
| 13 |       0_13 | score         |  1.00231  | 0.397532 |             0 |  10 |
| 14 |       0_14 | score         |  8.72149  | 0.182305 |             0 |  10 |
| 15 |       0_15 | score         | 11.7932   | 0.205478 |             0 |  10 |
| 16 |       0_16 | score         | 10.9242   | 0.445076 |             0 |  10 |
| 17 |       0_17 | score         |  0.136813 | 0.06524  |             0 |  10 |
| 18 |       0_18 | score         | 29.7467   | 0.433274 |             0 |  10 |
| 19 |       0_19 | score         |  1.66663  | 0.384765 |             0 |  10 |

Thank you so much for creating this wonderful library again and thank you so much in advance for reading our question! Let us know if anything is unclear.

**Comment by ldworkin** [comment]
Hi @nwrim ! Thank you for the detailed explanation. I was able to reproduce the exact behavior you're seeing. I believe what's happening is that, under the hood, we treat your parameters as floats, rather than ints. The model generates 10 float candidates, as expected. But then, we round them down to integers before returning the candidates to you. In this case, after rounding, many of the arms turn out to be the same. If this is indeed the case, then it's really the best we can do -- it means the model is confident that the best point is in this region, and it's not worth exploring elsewhere.

**Comment by ldworkin** [comment]
rpre

**Comment by ldworkin** [comment]
Oh and yes, your decision to use BatchTrial is correct and for exactly the right reason!

**Comment by nwrim** [comment]
Thank you so much for your answer! I will close the issue since your answer makes a lot of sense.

**Comment by nwrim** [comment]
Our team had been discussing this, and we have two new questions:

1) Is there a way to find out how many candidates were collapsed together for each arm after rounding? (i.e., is there a way we can know how many times the model suggested each arm, something like "arm 0 was suggested 4 times and was collapsed together")
2) What could be some potential downfall if we treat our parameter space as float search space, and do the rounding ourselves? Will this be different from using the int search space directly?

Thanks so much in advance! We really appreciate your effort in building this.

**Comment by bletham** [comment]
1. The candidates are collapsed when the arms are assembled into a GeneratorRun. That happens here in the `gen` method:
https://github.com/facebook/Ax/blob/e2808a9960a87831347658f6986ab76b9ded739a/ax/modelbridge/base.py#L680-L699

If you look at the GeneratorRun, the weight for each arm will be the number of times it was produced during the call to `gen`. So if there were 3 candidates collapsed to the same arm, you will see in the GeneratorRun a weight of 3 for that arm.

2. It would be fine in principal to give the search space to Ax as a continuous space and then do the rounding yourself, but I think there are two considerations.

The first is that when you pass the data back to Ax it will generally be important to associate it to the parameters that were actually evaluated (the rounded parameters) and not the ones that were requested by Ax. Consider a parameter x that is an int on [0, 5]. Suppose Ax generates arm "0_1" with x=2.3, and so then you round that to 2 and evaluate it. When you pass back to Ax the result of the valuation, you wouldn't want to say that is the result for arm "0_1", because it isn't the outcome for x=2.3, it is the outcome for x=2.0. So you would want to manually add an arm to the experiment that has x=2.0 and then use that arm name when providing the data back to Ax. Not having to do this is a benefit of having Ax do the rounding for you (so the arm it asks you for is the one you actually evaluate).

The second consideration is pretty subtle. When generating a batch of candidates, this is usually done sequentially and the acquisition value for each point in the batch is conditioned on the points that have already been generated for that batch. So if I select 2.3 as the first point in the batch, then when generating the 2nd I will condition on that and will not just choose 2.3 again. With rounding, we actually condition on the _rounded_ value during the batch generation. So: if the model generates 2.3 as the first point in the batch, then when generating the 2nd, it doesn't condition on 2.3 being in the batch, it conditions on 2 being in the batch. This doesn't fix all issues with duplication because, for instance, maybe when conditioning on 2.0 instead of 2.3, now 2.4 still has really high acquisition value and so I select that for the 2nd point and it also gets rounded down to 2. So I'm not sure how much worse of you will be by not rounding when conditioning within batch generation, but I wanted to flag this as the other way that doing rounding outside of Ax would be slightly different from doing it within Ax.

**Comment by nwrim** [comment]
Thank you so, so much for the detailed answer!
