### ISSUE TITLE
I think somethings wrong with the discussion of MKL in the documentation

### ISSUE THREAD

**Issue by justinkterry** [facebook/Ax#499]
In the readme, you say:

"_Recommendation for MacOS users_: PyTorch is a required dependency of BoTorch, and can be automatically installed via pip. However, **we recommend you install PyTorch manually before installing Ax, using the Anaconda package manager.** Installing from Anaconda will link against MKL (a library that optimizes mathematical computation for Intel processors). This will result in up to an order-of-magnitude speed-up for Bayesian optimization, as at the moment, installing PyTorch from pip does not link against MKL."

-Presumably such a speed up should impact Linux machines as well? This also may apply to macs even less given that new all macs don't have intel chips anymore.
-It's my understanding that the bayesian optimization shouldn't take a meaningful length of time under any normal circumstances?

Also a related question: Since this library is ultimately running off pytorch, I assume device is hard coded to be CPU to prevent using GPU capacity and crashing deep learning jobs?

**Comment by Balandat** [comment]
> Presumably such a speed up should impact Linux machines as well? This also may apply to macs even less given that new all macs don't have intel chips anymore.

It does, but the Linux pip install should properly take care of that. However, it is (or a least was) a known issue that a `pip install` on the Mac would yield binaries linked against the Mac BLAS/ATLAS libraries rather than Intel's MKL, hence we call out that gotcha explicitly. 

> It's my understanding that the bayesian optimization shouldn't take a meaningful length of time under any normal circumstances?

Depends on how expensive your jobs are, in the classic setting of very expensive/long function evaluations Bayesian Optimization will take a negligible amount of time to model and generate candidates. In other "high-throughput" settings it may may be important to keep things speedy though.

> Since this library is ultimately running off pytorch, I assume device is hard coded to be CPU to prevent using GPU capacity and crashing deep learning jobs?

It's not hard-coded, but the default device is `torch.device("cpu")`. This can be changed to a GPU device if desired. (this can provide speedups in the large-data regime / for certain models), but for standard Bayesian Optimization running things on the CPU is perfectly adequate.

**Comment by justinkterry** [comment]
Thanks a ton

**Comment by justinkterry** [comment]
Thanks a ton; it would appear that I was wrong here.
