### ISSUE TITLE
Algorithm for constrained BO in Service API

### ISSUE THREAD

**Issue by IgorKuszczak** [facebook/Ax#526]
Dear Authors,

I have been using the framework for the last few months in an academic project and it has been a great experience so far. Thank you for that. 

I would like to know what kind of algorithm is used within the Service API to deal with the outcome constraints. I have seen some clues about it in issue #324 but would like to know for sure. Thanks in advance!

**Comment by lena-kashtelyan** [comment]
cc @sdaulton as modopt oncall

**Comment by sdaulton** [comment]
Hi @IgorKuszczak, if you are using Sobol + GPEI, the algorithm being used is Noisy Expected Improvement. This paper provides details on how outcome constraints are accounted for during candidate generation: https://projecteuclid.org/journals/bayesian-analysis/volume-14/issue-2/Constrained-Bayesian-Optimization-with-Noisy-Experiments/10.1214/18-BA1110.full. If only Sobol is used (e.g. because there are lots of categorical parameters), then outcome constraints are not addressed in any way. The Sobol generator does not fit a surrogate model, so it has no way of knowing/predicting which quasi-random points will satisfy the outcome constraints.
