### ISSUE TITLE
[Question] Documentation for Modelbridge.Factory Models

### ISSUE THREAD

**Issue by nwrim** [facebook/Ax#551]
I have been looking through the Ax documentation, such as [this one](https://ax.dev/docs/models.html) to find specifics about the "out-of-shelf" models that Ax supports, such as `ax.modelbridge.factory.get_GPEI`. I was wondering where I could find some details about these models that Ax offers, such as what Kernel it is using (I am guessing ARD Matérn 5/2 kernels as it is the default in BoTorch, but I was not able to find it stated in Ax). Could you point me to where this documentation is (or is it in preparation)? Sorry for a such trivial question.

Also, I read from few papers published by Facebook that showed great work in [Noisy Expected Improvement](https://projecteuclid.org/journals/bayesian-analysis/volume-14/issue-2/Constrained-Bayesian-Optimization-with-Noisy-Experiments/10.1214/18-BA1110.full) (and qNEI). Are there any plans in implementing GP+NEI and GP+qNEI as "out-of-shelf" models in Ax like get_GPEI (or is get_GPEI actually using NEI - I read that `ax.models.torch.botorch.BotorchModel` uses NEI as default acquisition function, but GPEI just said "EI" in documentation and tutorials)?

**Comment by qingfeng10** [comment]
Hey @nwrim, thanks for your interest! [`get_GPEI `](https://fburl.com/qeftq4up) uses all the defaults when constructing the `BotorchModel`. The defaults can be found in [`__init__`](https://fburl.com/4jp9kivc). Therefore, if you want to dig  into what GP model, or acquisition function it uses,  you can find in `ax.models.torch.botorch.botorch_defaults`.  It uses the same SingleTaskGP as in BoTorch. 

To use the model or acquisition function you want, [`get_botoch`](https://fburl.com/3y8ohrqc) is a good choice that you can pass your own `acqf_constructor`. To handle noisy observations, we use `qNEI` which is the implementation of the Noisy Expected Improvement.

**Comment by nwrim** [comment]
Thanks for the response, @qingfeng10! Somehow, the links you posted all show "Facebook Sign in" page. I don't think I can access it. Could you check the URLs again?

**Comment by qingfeng10** [comment]
I updated the links. Do they work now?

**Comment by lena-kashtelyan** [comment]
Hi @nwrim, for default model components we use, you can check specifically:
- which BoTorch surrogate model is used here: https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_defaults.py#L47,
- which acquisition function is used here: https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch.py#L240 (it's NEI, Noisy Expected Improvement), by default.

> (or is get_GPEI actually using NEI - I read that ax.models.torch.botorch.BotorchModel uses NEI as default acquisition function, but GPEI just said "EI" in documentation and tutorials)?

Yep it is, as linked above, great catch!

We have some documentation on the models we offer off-the-shelf (which you linked above), which states incorrectly that our default GPEI uses EI and not NEI as you point out. We will make a note to change that!

**Comment by nwrim** [comment]
Thanks for all the help! The links (both from @qingfeng10 and @lena-kashtelyan) work well!

**Comment by zeyueN** [comment]
Hey, thanks for the great work and also the links above! Piggybacking on this since it's somewhat related. When will the next release be that includes [_get_acquisition_function](https://github.com/facebook/Ax/blob/9c408c6c1cdf690c7a0510c012f19b9e52a2028e/ax/models/torch/botorch_defaults.py#L203)? The current v0.1.20 seems to have `qNEI` [hardcoded](https://github.com/facebook/Ax/blob/c428eb101954c3f6a14d7e8d3f4995447290998e/ax/models/torch/botorch_defaults.py#L239).

And I guess a more general question is that, why is there no user-facing function that makes swapping out acquisition functions easier? It seems all the utilities are already there.

**Comment by ldworkin** [comment]
@zeyueN , we'll push a new version in the next week or two. Will the addition of that function address your use case, or do you need anything else? What is it you're looking to accomplish? (cc @lena-kashtelyan, sounds like a modular BoTorch use case.)

**Comment by zeyueN** [comment]
@ldworkin Thanks for the reply. For simple **named** botorch acquisition functions, yes it partially addresses it. What I wanted to do is a quick way of swapping and testing different acquisition functions. Even with the [_get_acquisition_function](https://github.com/facebook/Ax/blob/9c408c6c1cdf690c7a0510c012f19b9e52a2028e/ax/models/torch/botorch_defaults.py#L203) released, it only allows named botorch acquisition functions; replacing with custom botorch acquisition function is still a bit cumbersome since I have to copy the code in `_get_acquisiton_funtion` and transform the objective transform myself.

**Comment by lena-kashtelyan** [comment]
@zeyueN, you might be interested in https://github.com/facebook/Ax/issues/363 –– the functionality discussed in that issue is still in beta-stage but it lets one use a custom BoTorch acquisition function and/or surrogate model (and mix-and-match those subcomponents) as part of one modeling setup in Ax (@ldworkin mentioned this above as 'modular BoTorch' –– our recent effort to allow for easy combining of various BoTorch subcomponents in Ax).

**Comment by lena-kashtelyan** [comment]
> https://github.com/facebook/Ax/issues/363

That seems worthy of a separate issue and a bit more detail so folks on the modeling and optimization side can chime in.

**Comment by zeyueN** [comment]
Thanks for the pointer @lena-kashtelyan . Went through the tutorial and I think the new features addresses most of my questions.

In terms of greediness tuning, I can see the new `GenerationStrategy` can sort of do that by switching acquisitions functions midway. I guess I'm imagining a more "dynamic", condition-based, step-switching mechanism (e.g. switch to next step after detecting no improvements for k steps).

I'll provide my feedback for these in a new issue after playing around with them for a bit.

**Comment by lena-kashtelyan** [comment]
> In terms of greediness tuning, I can see the new GenerationStrategy can sort of do that by switching acquisitions functions midway. I guess I'm imagining a more "dynamic", condition-based, step-switching mechanism (e.g. switch to next step after detecting no improvements for k steps).

Very interesting to hear this; we actually have been planning to support something like what you describe, a dynamic generation strategy, but we do not yet have a timeline for that project.

I'll provide my feedback for these in a new issue after playing around with them for a bit.

> It will be great to hear your thoughts on this, please do!
