### ISSUE TITLE
How to instruct Ax to stop searching in a given area of the search space

### ISSUE THREAD

**Issue by Jason-Waldrop** [facebook/Ax#578]
How can I configure AX to ignore the current trial, when my function fails to compute a valid number?

My evaluation_function frequently has numerical instabilities for some parameters and I want AX to stop searching in this area of the search space. I cannot use parameter constraints, since I do not know in advance where the instabilities occur.

**Comment by Balandat** [comment]
Do you have a sense of what a natural "bad" outcome value is for your function (e.g. say if you were to train some ML model that could be the score of the untrained model). You could then use that value for the failed trial rather than just ignoring it. This is kind of a crude approach and there are more sophisticated ones, but those are more involved and we currently don't have them hooked up in Ax.

**Comment by Jason-Waldrop** [comment]
I thought of that approach, but it requires that the values is specified before running the optimization. And ideally this number is as close as possible to a "bad" outcome. Actually my first hacky-solution was to just use a very big number, but if the number is too large (1e50), Ax will throw numerical instabilities errors (understandable).

And as I could not find anything in the documentation, I wanted to ask if there is a better way to do it.

So from my side this issue can be closed, as my question is answered. Thanks!
