### ISSUE TITLE
Augmenting trial run metadata with metadata from `Runner.stop` call

### ISSUE THREAD

**Issue by ugurmengilli** [facebook/Ax#595]
Hi, I would like to thank you for such a detailed abstraction of experimentation steps. Although it needs a very deep dig of the modules until understanding the purpose of a component (sometimes I misinterpret too), eventually, all pieces fit beautifully.

I want to discuss a usage case that relies on the implementation of a `Runner`. I checked that the only required method to implement is `Runner.run()`, which may return some metadata about deployment. I assume that I can use this method to get the arms of the trial and prepare the actual parameters to configure and start the actual process. Then, possibly it collects some other metadata during running, which will later be used to compute the cost of a metric using `Metric.fetch_trial_data()`. This part may not be as I predicted but, unlike synthetic metrics that implement an offline function `f()`, I couldn't think of another way to handle process data.

In a specific case, I want to use `Runner.run()` to open a TCP connection on a real-time target computer and deploy the required parameters. However, the target cannot transfer real-time process data before stopping the process because it would overload the computer. So, `Runner.run()` will not return any process metadata. Conceptually, I would use `Runner.stop()` to stop the process, close the connection and collect the data that my metric will need to compute its cost. However, `BasicTrial.complete()` does not collect any metadata.

As a work-around, I would implement the `Runner.run()` to execute all the above processes, but then, what would be the purpose of `Runner.stop()` because eventually, I will define something like `stop_my_process()` and call it in `Runner.run()`.

Probably, I will work this out by implementing a `MyTrial` that overrides only `.complete()` such that:
```
...
metadata = not_none(self._runner).stop(self)
self.update_run_metadata(metadata) if metadata else pass
...
```
But I would like to get your comments about it: would it be considered directly in `BasicTrial` in the future, or is there any other way to do it more ax-like?

**Comment by lena-kashtelyan** [comment]
Hi, @ugurmengilli! 

>  Although it needs a very deep dig of the modules until understanding the purpose of a component (sometimes I misinterpret too), eventually, all pieces fit beautifully.

That sounds like our docs could use some improvement : )

Usually, the way most flows work in Ax is:
- `Runner.run` deploys some process that evaluates the trial and returns trial metadata about that process (for example, a job ID),
- `Metric.fetch_trial_data` then leverages that metadata to retrieve the data for the trial when it becomes available (some metrics query data only for `COMPLETED` trials and some –– for `COMPLETED` and `RUNNING`, that depends on the metric implementation –– specifically on the `is_available_while_running` method).

My understanding is that your flow is different because the metadata about the job/process you use to evaluate the trials is only available when the process is completed –– is that right?

If so, I think one way to implement what you are looking to implement would be to update the trial run metadata within `Runner.stop`? Something like this:
```
def stop(self, trial: BaseTrial) -> None:
        metadata = stop_my_process()
        trial.update_run_metadata(metadata)
```

This would allow you to not need to add a custom trial –– something you should never really need to do in Ax.

----

With that said, I think your suggestion to incorporate recording trial metadata in `Runner.stop` makes complete sense; that method should return a metadata dict like `Runner.run` does, since metadata could come from stopping the process as well as from starting it (we just haven't had that use case before). We'll incorporate this into a future version of Ax, and in the meantime, my suggestion above should work well for you, I believe.

**Comment by ugurmengilli** [comment]
> My understanding is that your flow is different because the metadata about the job/process you use to evaluate the trials is only available when the process is completed –– is that right?

Yes, and your temporary suggestion equally works until future updates.
 
> > This part may not be as I predicted but, unlike synthetic metrics that implement an offline function f(), I couldn't think of another way to handle process data.
> 
> I'm not 100% sure I understand what you mean by "handling process data" here...

I meant "calculating the metric cost based on the trial metadata" by "handling" as you correctly continued in your answer. Thank you.

> That sounds like our docs could use some improvement : ) If you have thoughts on what we should add or notes on what parts you found confusing/lacking, please let us know!

The main problem was I read everything on the website site months ago, and I didn't realize that you were updating the site, so I didn't bother going through the same content. Instead, I felt that I had to dig the code. Although that worked pretty well in the end, a single trial add-run-fetch cycle made me go through several distracting BoTorch details while my major concern was first to understand the experimentation workflow. Recently, I realized a new content "multi-objective opt.". Now, I saw that you have completely changed the order of the content. So I will reread everything and let you know if have any problem with the documentation.

An "updates" section with a date of the update on the main page would probably be very beneficial to track the changes to the website. But periodically checking [this folder](https://github.com/facebook/Ax/tree/master/website) also works for me.

**Comment by lena-kashtelyan** [comment]
> An "updates" section with a date of the update on the main page would probably be very beneficial to track the changes to the website.

That's a great idea and is actually on our roadmap for the second half of this year, so stay tuned!

**Comment by Balandat** [comment]
@ugurmengilli I just realized that I happened to work on exactly this feature without actually being aware of this issue. I should be able to put out a PR some time soon, would be great to get your eyes on it :) Will be sure to tag you.

**Comment by Balandat** [comment]
I added a `stop_metadata` dict to trial and expanded the runners' `stop` method to fill that: https://github.com/facebook/Ax/commit/165c67293a4cbdbd05485d8c3d107ab19c5be0c3

**Comment by lena-kashtelyan** [comment]
Keeping this open actually until a stable version release, but as @Balandat said above, the fix for this is in on master!

**Comment by lena-kashtelyan** [comment]
This is now part of latest stable, 0.2.1.
