### ISSUE TITLE
Changing the search space when using the AxClient

### ISSUE THREAD

**Issue by jusa2k** [facebook/Ax#699]
First of all thank you very much for this great tool, I do really appreciate it! I was wondering if there is a way of modifying the parameter constraints and outcome constraints and utilising the data from already ran experiments when using the AxClient?

**Comment by lena-kashtelyan** [comment]
Hi, @jusa2k! We're so glad Ax is helpful to you!

> I was wondering if there is a way of modifying the parameter constraints and outcome constraints ... when using the AxClient

There is not a specially supported API for this as part of Service API/AxClient, but you should be able to modify some parts of the search space directly by accessing `ax_client.experiment.search_space`. You can see available methods on the `SearchSpace` API reference page: https://ax.dev/api/core.html#searchspace. I think all the functionality there should be compatible with `AxClient` optimizations, but it's not something we tested extensively, so let us know if you run into any issues!
 
> I was wondering if there is a way of ... utilising the data from already ran experiments when using the AxClient?

Alternatively, there is an approach of creating a new experiment and carrying over trials from a previous experiment via `AxClient.attach_trial` (to add a trial), then `AxClient.complete_trial` (too add its data), see example in [this section of the Service API tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html#Special-Cases). This way, your new experiment would have the constraints you want from the beginning, but can still leverage the data from the previous experiment that had different constraints. Just be mindful that if you do this, it's best to not modify the evaluation function you use to obtain the data for the trials, since otherwise the data from previous experiment will not be directly compatible with the new one.

**Comment by jusa2k** [comment]
Thank you very much for your quick response! I think I'll go with the attach_trial/complete_trial approach.

Many thanks,
Jusa

**Comment by lena-kashtelyan** [comment]
Of course, and feel free to reopen the issue if anything doesn't work as expected or you need more help!
