### ISSUE TITLE
How to learn which model Ax used for a given optimization?

### ISSUE THREAD

**Issue by bhaskatripathi** [facebook/Ax#708]
Hi,
I am using the below code to optimize my neural network model and I am able to see the optimized results. I can also use the best parameters given by AE and improve my model. However, for the purpose of explanation in the research paper, I am not able to figure out which type of optimization was actually used in the multi-arm bandit configuration of AE client.

```
ax_client = AxClient()
# create the experiment.
ax_client.create_experiment( name="keras_experiment", parameters=parameters, objective_name='keras_cv', minimize=True)
no_of_trials=12
for i in range(no_of_trials):
    parameters, trial_index = ax_client.get_next_trial()
    ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters,train_X,train_y,val_X, val_y))
# save results to json file.
ax_client.save_to_json_file()

ax_client.get_trials_data_frame().sort_values('trial_index') # PRINTING/VISUALIZING THE RESULTS - look at all the trials.
#VIEW THE BEST VALUES OF HYPERPARAMETERS
best_parameters, values = ax_client.get_best_parameters()
# the best set of parameters.
for k in best_parameters.items():
  print(k)
print()
# the best score achieved.
means, covariances = values
print(means)
#plot the evolution of the keras_cv score over iterations. view the score reaches the minimum value 
render(ax_client.get_optimization_trace()) 
``` 
Please help / provide the resource which can help me understand which algorithm was actually run ? Was it Bayesian Opt or some other algorithm?

**Comment by lena-kashtelyan** [comment]
Hi again @bhaskatripathi, sorry it took a while to get back to you –– we didn't see your response since you closed the issue.

I think there is some confusion; Sobol + BO_MIXED does not mean EB or TS are applied –– in fact, they are not. It's just this specific section that pertains to BO_MIXED: https://ax.dev/docs/models.html#support-for-mixed-search-spaces-and-categorical-variables, not everything in that doc. Please let us know here if you have more questions, we want to make sure to not mislead you about this.

**Comment by bhaskatripathi** [comment]
Hi @lena-kashtelyan , I am going through the link you shared. Will get back to you in case I have any questions.

**Comment by lena-kashtelyan** [comment]
@bhaskatripathi, please reopen this issue if you have any follow-ups : ) BO_MIXED doesn't use EB or TS, so just wanted to make sure nobody walked away from this issue confused about that!
