### ISSUE TITLE
Understanding BO_mixed

### ISSUE THREAD

**Issue by beef-broccoli** [facebook/Ax#711]
Hi there, 

Sorry if this has already been answered before, but could you help me understand BO_mixed a little better in terms of how it works? I read the doc on generation strategy and I understand the separate kernel part, but for each combination of categorical values, is it still doing Bayesian optimization by fitting a GP model with acquisition function like EI? 

Also a quick question on the actual usage case, when will it get defaulted to BO_mixed instead of GPEI? Does ax consider the overall number of categorical variables compared to continuous ones? 

Thanks in advance for your help

**Comment by dme65** [comment]
Hello,

> Sorry if this has already been answered before, but could you help me understand BO_mixed a little better in terms of how it works? I read the doc on generation strategy and I understand the separate kernel part, but for each combination of categorical values, is it still doing Bayesian optimization by fitting a GP model with acquisition function like EI?

The way BO_MIXED is currently implemented we first fit a GP model using separate kernels for the ordinal (float/int) and categorical parameters. To optimize the acquisition function we enumerate the possible options for the categorical variables, optimize the acquisition function over the ordinal variables for each combination, and pick the best one. Imagine that we have two categorical variables, one with 2 options and one with 4 options. BO_MIXED will then optimize the acquisition function over the ordinal variables for the 2 x 4 = 8 different combinations and then pick the candidate with the best acquisition function value. This works well when there are only a few categorical variables, each with a few options, but things can get out of hand quickly since we are enumerating the different combinations.

**Comment by lena-kashtelyan** [comment]
Hi again @beef-broccoli, please let us know if your question wasn't fully answered! If you do have follow-ups, please reopen the issue to make sure we see them.
