### ISSUE TITLE
Multi-Objective Optimization using qNEHVI + SAASBO

### ISSUE THREAD

**Issue by zzzbobml** [facebook/Ax#712]
From the [original paper](https://arxiv.org/pdf/2103.00349.pdf), it seems that SAASBO is used for dimensionally reduction over a large number of dimensions. 

Would it be possible to use it for dimensionality reduction in other algorithms other than SVM (for example, decision trees)? 
For example, let's say some of the dimensions we optimize for are binary values (1 indicating the corresponding feature is used, and 0 otherwise). 

Would this method be able to find an approximate solution of the problem, even if the space of possible solutions is exponential in complexity?

**Comment by danielcohenlive** [comment]
@Balandat would definitely know more about this, but Ax is designed for more basic use cases and built on top of [botorch](https://botorch.org/).  If you want to create your own models and customize algorithms, botorch would be a better choice than Ax.

**Comment by lena-kashtelyan** [comment]
cc @dme65 on this one

**Comment by dme65** [comment]
Hi zzzbobml,

> From the [original paper](https://arxiv.org/pdf/2103.00349.pdf), it seems that SAASBO is used for dimensionally reduction over a large number of dimensions.

SAASBO isn't directly used for dimensionality reduction in the paper, but the SAAS prior assumes that only a few parameters are important which avoids overfitting and allows us to use it for Bayesian optimization with hundreds of parameters. The GP lengthscales give you an idea of what parameters are important and you can potentially rely on them for (axis-aligned) dimensionality reduction if you like, see the bottom of the SAASBO tutorial here: https://github.com/facebook/Ax/blob/main/tutorials/saasbo.ipynb.

> Would it be possible to use it for dimensionality reduction in other algorithms other than SVM (for example, decision trees)? For example, let's say some of the dimensions we optimize for are binary values (1 indicating the corresponding feature is used, and 0 otherwise).

In principle, yes. One thing to be careful with here is that Ax deals with discrete variables by using continuous relaxation, so boolean variables are particularly difficult for us to deal with. This means that the performance in a Bayesian optimization loop may not be great, but it is still possible that the SAAS model is able to identify the most important parameters. If you have a large number of boolean variables then you may have better luck with our BO_MIXED method or a method tailored for such problems such as BOCS: https://arxiv.org/pdf/1806.08838.pdf. We are actively working on better methods for mixed-search spaces since we have many such use-cases.

**Comment by lena-kashtelyan** [comment]
@zzzbobml, did we answer your question? Please let us know if you have any follow-ups; if so, please reopen the issue so we see your comments.
