### ISSUE TITLE
Can I include prior knowledge?

### ISSUE THREAD

**Issue by Stefan2016** [facebook/Ax#723]
Hi all,

Thanks for the great project.

I wonder if there is a way to include prior knowledge. E. g., I already have run a couple of experiments (randomly / by intuition) which might have some insights for the BO algorithm. Can I provide this data somehow for a “pre training”?

**Comment by lena-kashtelyan** [comment]
Hi @Stefan! Check out the second part of my response here: https://github.com/facebook/Ax/issues/699#issuecomment-929378581. 

If that does not work for your case, please elaborate on what insights you would want to use for pre-training. Ss it a specific configuration you would want to make sure that Ax tries (because you think it will perform well, for example)? Is it knowledge about which parameters matter more than others (this one is trickier)?

**Comment by lena-kashtelyan** [comment]
Hi again @Stefan2016! I see I tagged you incorrectly last time, so re-tagging you. Please let us know if you have any follow-up questions after you check out the comment I linked above.

**Comment by lena-kashtelyan** [comment]
We'll consider this one answered since it's inactive; if you have more questions or follow-ups, please reopen this issue, @Stefan2016!
