### ISSUE TITLE
Retrieve trained surrogate model after BO

### ISSUE THREAD

**Issue by aaditya8959** [facebook/Ax#725]
I followed the Service API example and implemented BO after modifying it for my specific case involving 5 parameters and 1 metric. How can I now obtain the trained surrogate model at the end of the optimization to make predictions on new parameter combinations?

**Comment by lena-kashtelyan** [comment]
Hi @aaditya8959! You can use: `ax_client.generation_strategy.model.predict(observation_features=[...])`, which will direct you to [this method](https://fburl.com/r447x17o) ([API docs](https://ax.dev/api/modelbridge.html#ax.modelbridge.base.ModelBridge.predict)).

To convert parameterizations to `ObservationFeatures` ([API docs](https://ax.dev/api/core.html#ax.core.observation.ObservationFeatures))  –– since that is what `ModelBridge.predict` expects as an argument) –– do: `ObservationFeatures(parameters=my_parameterization_dict)`. Note that you will always need to pass a list of observation features to `predict`, even if you are only looking to make a prediction for one parameterization.

**Comment by aaditya8959** [comment]
Thank you @lena-kashtelyan. I will try out your suggestion.

**Comment by aaditya8959** [comment]
Hi @lena-kashtelyan. I created the observation features from the parametrization and passed it as a list to 'predict' to successfully obtain the means and covariances for a new set of parameters. Thank you!

**Comment by lena-kashtelyan** [comment]
Wonderful!
