### ISSUE TITLE
saasbo_nehvi.ipynb couldn't be loaded "unreadable Notebook..NotJSONError" 

### ISSUE THREAD

**Issue by hanochk** [facebook/Ax#729]
Hi, can't load under Jupyter notebook under chrome ububtu 20.04
![image](https://user-images.githubusercontent.com/8217391/142770117-8effa97b-44d2-45db-80d4-d20ca8f5bc9d.png)

**Comment by Balandat** [comment]
This looks very much like an HTML file you're trying to open. How exactly are you getting this error? It seems like you might have saved the rendered tutorial rather than downloaded the tutorial file? I just verified that loading https://github.com/facebook/Ax/blob/main/tutorials/saasbo_nehvi.ipynb from a clone of the repo works.

**Comment by hanochk** [comment]
Hi, Let me clone and recheck, thanks.
Best regards,
Hanoch Kremer
https://hanochk.github.io/about

**Comment by lena-kashtelyan** [comment]
Hi @hanochk, were you able to reproduce the issue?

**Comment by hanochk** [comment]
Hi Lena, Sure I can
Best regards,
Hanoch Kremer
https://hanochk.github.io/about

**Comment by hanochk** [comment]
As a matter of fact, it reproduced also with saasbo.ipynb
Best regards,
Hanoch Kremer
https://hanochk.github.io/about

**Comment by hanochk** [comment]
Oh sorry that issue  couldn't be loaded is fine now and solved!
Best regards,
Hanoch Kremer
https://hanochk.github.io/about

**Comment by lena-kashtelyan** [comment]
Okay sounds like this is resolved; feel free to reopen this if I misunderstood you @hanochk!
