### ISSUE TITLE
Ok to add stochastic repeated measurements for fixed input parameters?

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#752]
If you have a single wet-lab sample, and you make multiple property measurements on it (e.g. 5 repeated measurements of strength), would it be considered best practice to add all 5 measurements as separate trials?

**Comment by lena-kashtelyan** [comment]
Something you might see if you have a bunch of repeated observations are errors like the one mentioned here: #228. If it does happen, please let us know here with a copy of a printout of exp_to_df output for your experiment (so we can see what your data looked like).

**Comment by sgbaird** [comment]
Thanks! If I do run into issues, I'll let you know.

As a follow-up, if each measurement has its own uncertainty (let's just assume this is equipment resolution) which is (potentially much) lower than that of the uncertainty associated with each repeated measurement, should I leave that out, or should that be incorporated as well? 

If the equipment resolution is an order of magnitude or two lower than the uncertainty of the repeated measurements, it's probably a moot point and can be safely ignored.

I wonder if it would be "safe" to add it to the SEM.

**Comment by lena-kashtelyan** [comment]
cc @Balandat and @qingfeng10 on that question

**Comment by Balandat** [comment]
> If the equipment resolution is an order of magnitude or two lower than the uncertainty of the repeated measurements, it's probably a moot point and can be safely ignored. I wonder if it would be "safe" to add it to the SEM.

So since we're looking at this in a black box fashion the model wouldn't really understand the difference between the noise caused by the repeated measurements and the noise caused by the observations. Ideally you would provide the total noise level for a repeated observation (law of total variance). If you don't know that then that's fine, just provide a NaN for unknown and the model should be able to infer the total noise level. 

However, if you pass in a SEM the model will consider that as the total noise level. So if you pass a very small SEM for the measurement error but the variance in the repeated evaluations is very large, then you may up in a place where the observed data for the repeated observations is totally inconsistent with the high variance observations. Likely the model will break in such a situation due to difficulties maximizing the likelihood of the data under the parameters. 

Going back to the original question: If you have a few observations at the same configuration it should be fine to add them as separate trials (either with an inferred NaN noise level or the proper SEM for the repeated observations). However if you have a large number of repeated observations per configurations you'll likely start to see both scalability issues (things will get slow), and numerical issues (b/c the repeated observations will render the covariance ill-conditioned). So if you have plenty of observations per configuration the best practice would be to use those to estimate the mean and SEM, and then to report that mean + sem as a single observation.

**Comment by sgbaird** [comment]
@Balandat, thanks for your thorough answer. This helps a lot! I think I'll need to brush up on law of total variance. An application (uncertainty due to equipment resolution and uncertainty due to e.g. the physical stochastic nature of the measurement) is a bit elusive to me, but that also helps me realize that perhaps there's no need to add in that uncertainty - since the measured outcome would incorporate deviations due to both equipment resolution and physical stochasticity of the measurement. The equipment resolution is essentially a-priori information and the physical stochasticity isn't known very well except by the repeated measurements, but a single measurement actually is affected by both. I appreciate your point about reducing to a mean and SEM if there are many observations. Very actionable suggestions.
