### ISSUE TITLE
Request to make `Experiment._properties` a public attribute and question about `Trial._properties`

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#775]
This is more a request for feature(s).
Any reasonable real-life scenario of use requires an _extensive_ use of 'properties' attribute of the Experiment object. I'm not sure why it has not been made public. Can it be made public? In the same vein: the Trial object has a field(column) 'properties' in the SQA store table, but the object doesn't have such attribute... Can you just add this attribute/property? As far as I understand your implementation of ORM it must 'automagically' be mapped to the column in the 'trial_v2' table by itself... or with very little work to do.

**Comment by lena-kashtelyan** [comment]
Hi @alxfed! Could you elaborate a bit on this point?

> Any reasonable real-life scenario of use requires an extensive use of 'properties' attribute of the Experiment object

Specifically, I'm curious about what needs to go into the experiment properties for you (just approximately), so we can make sure there isn't a pre-defined place for those properties. Generally, we discourage putting a lot of stuff into properties because they just get JSON-serialized and dumped into the DB as a whole, but we could certainly reconsider this, it would just be helpful to learn what the use case is.

> the Trial object has a field(column) 'properties' in the SQA store table, but the object doesn't have such attribute...

Trial does actually have properties, it just lives in `BaseTrial` class: https://github.com/facebook/Ax/blob/main/ax/core/base_trial.py#L243. For these too, there might be a better place to put them (often times, we put evaluation job-related information into `trial.run_metadata`).

**Comment by alxfed** [comment]
I have an experimentation 'microservice' that samples data for individual experiments from dozens of schemes in DWH... and in several ways depending on the type of a trial. An 'online' (which it manages itself with the help of a scheduler built on APScheduler), 'offline' and 'multi_mode'. 
In this case you just have to attach info about the original sources of the data and configuration(s) of your 'Sampler' as I call it, to the experiment (and in many cases to the trial too, because trials may use all sorts of peculiar configurations for data acquisition).
Thank you for the tip about the BaseTrial.

**Comment by lena-kashtelyan** [comment]
All of that makes sense. I think probably the move is to try to put what you can of that information, into `trial.run_metadata`, and the rest –– into `Experiment._properties` or `Trial._properties`, as you suggest. If you wanted to put up a PR adding the following to `Experiment` and `Trial` (+ rudimentary unit-tests), I'd be happy to merge it!
```
@property
def properties(self) -> Dict[str, Any]:
    return self._properties

def update_properties(self, update_with: Dict[str, Any]) -> None:
    self._properties.update(update_with)
```

**Comment by alxfed** [comment]
I understand. That's exactly how I save it (sometimes after doing an `update_properties_on_experiment()` ).

**Comment by alxfed** [comment]
Actually it looks like doing `save_or_update_trial()` after modifying the `trial._properties` will work best, @lena-kashtelyan .

**Comment by lena-kashtelyan** [comment]
That should work, yes! Just note that that function won't update properties of experiment if you modify those, only the trial's.

**Comment by alxfed** [comment]
Yep.

**Comment by lena-kashtelyan** [comment]
Merged into wishlist master-task.
