### ISSUE TITLE
Parallel evaluations with 'sequential' acquisition functions in Service API

### ISSUE THREAD

**Issue by IgorKuszczak** [facebook/Ax#776]
Hello, 
I am exploring the options for implementing BO with parallel evaluations and found issue #179, where a method for requesting multiple 1-arm trials in Service API is described. I am attaching the solution suggested by @lena-kashtelyan below for convenience.

```
# Generate 5 trials.
trials_to_evaluate = {}
for _ in range(5):
    parameterization, trial_index = ax_client.get_next_trial()
    trials_to_evaluate[trial_index] = parameterization

# Computing results would actually evaluate your trials in parallel,
# you'd implement it in whatever way works for your setup.
results = { 
    trial_index: evaluate(parameterization)
    for trial_index, parameterization in trials_to_evaluate
}

# Update them all with data at once.
for trial_index in results:
    ax_client.complete_trial(trial_index, results.get(trial_index)
```

I would like to know **how  ax_client.get_next_trial() selects the parameterizations when using 'sequential' acquisition functions** such as Expected Improvement. Does it suggest the local maxima of the acquisition function, or is it something more complicated? I am aware of the parallel q-EI and will likely use it in my work. However, I am curious how parallelisation is achieved in this context.

**Comment by lena-kashtelyan** [comment]
> I would like to know how ax_client.get_next_trial() selects the parameterizations when using 'sequential' acquisition functions such as Expected Improvement. Does it suggest the local maxima of the acquisition function, or is it something more complicated? I am aware of the parallel q-EI and will likely use it in my work. However, I am curious how parallelisation is achieved in this context.

Let me loop in @Balandat and @dme65 to answer that one!

In the meantime, I'll suggest a new piece of functionality that hasn't yet made it to our tutorials; you can now generate multiple trials at once like this:
```
# Generate as many trials as currently possible 
# (given restrictions on maximum parallelism and steps in generation strategy)
trial_index_to_parameterizatoin trials_to_evaluate = ax_client.get_next_trial() # Format: { trial index --> parameterization}
trials_to_evaluate[trial_index] = parameterization

# Computing results could actually evaluate your trials in parallel,
# you'd implement it in whatever way works for your setup.
results = { 
    trial_index: evaluate(parameterization)
    for trial_index, parameterization in trials_to_evaluate
}

# Update them all with data at once.
for trial_index in results:
    ax_client.complete_trial(trial_index, results.get(trial_index)
```

**Comment by dme65** [comment]
> I would like to know how ax_client.get_next_trial() selects the parameterizations when using 'sequential' acquisition functions such as Expected Improvement.

Sequentially generating a batch of q candidates means we generate one candidate at a time by selecting the best candidate according to the acquisition function while conditioning on the previously selected points.

To break this down, imagine q=3.
1) We will select the first candidate `x_1` by optimizing the traditional expected improvement.
2) The second candidate `x_2` is then selected by optimizing expected improvement conditioning on the fact that we have already selected `x_1`. If we didn't condition on this we would like just end up selecting `x_1` again.
3) To select the third candidate `x_3` we optimize expected improvement conditioning on having already selected `x_1` and `x_2`.

Instead of selecting them sequentially in this fashion we can also select them jointly by optimizing the acquisition function over `x_1`, `x_2`, and `x_3`. This comes at a much higher computational cost, especially if q is large, and we often find that selecting them sequentially works very well which is why we usually prefer doing that.

**Comment by IgorKuszczak** [comment]
Thank you for the quick response! It clarified my doubts :)
