### ISSUE TITLE
`BOTORCH_MODULAR` with `Surrogate(SingleTaskGP)` doesn't support `ax.plot.feature_importances.plot_feature_importance_by_feature`, is ARD kernel still used?

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#780]
https://github.com/facebook/Ax/issues/771#issuecomment-1011742002

I tried using e.g. `SingleTaskGP`, but I was getting an error message that feature importances weren't supported. However, I'm pretty sure it's still an ARD kernel based on the docs. Am I missing something basic?

**Comment by bernardbeckerman** [comment]
@sgbaird Thanks for reporting this! `ax.plot.feature_importances.plot_feature_importance_by_feature` requires that the model bridge you are using has implemented a `feature_importances` method, however you're using `BOTORCH_MODULAR`, which does not implement this method. As a result, `plot_feature_importance_by_feature` will fail regardless of the surrogate you use. Does that make sense?

**Comment by sgbaird** [comment]
Thanks for the reply! Yes, that definitely makes sense. Any idea where I could get the raw ARD lengthscales from the surrogate model?

**Comment by bernardbeckerman** [comment]
I just touched base with @lena-kashtelyan - `BOTORCH_MODULAR` not supporting this behavior is an oversight and we'll definitely add support for it. In the mean time, it may be useful to follow the `feature_importances` method of another modelbridge (e.g., [BotorchModel](https://github.com/facebook/Ax/blob/1584e5f4edb315fb34aa11bebb6967a8ba38c18b/ax/models/torch/botorch.py#L498-L514) to retrieve the feature importances you're looking for. If that's not clear please let me know and I can create a working example for you. If it does work, please post your code here for posterity!

**Comment by lena-kashtelyan** [comment]
Building off of @bernardbeckerman's suggestion above, the way you would apply the contents of [`BotorchModel.feature_importances`](https://github.com/facebook/Ax/blob/1584e5f4edb315fb34aa11bebb6967a8ba38c18b/ax/models/torch/botorch.py#L498-L514), is, given an `AxClient`, using:
`ax_client.generation_strategy.model.model.surrogate.model` instead of `self.model` that instance method. 

Also, we know `ax_client.generation_strategy.model.model.surrogate.model` is a little ridiculous : ) There, `ax_client.generation_strategy.model` gives the model bridge, then `ax_client.generation_strategy.model.model` gives the `BoTorchModel` in Ax, then `ax_client.generation_strategy.model.model.surrogate.model` gives the underlying `Model` component from BoTorch (e.g. `SingleTaskGP`).

**Comment by sgbaird** [comment]
Thank you @bernardbeckerman and @lena-kashtelyan. Also, I get that Ax is very high-level, modular, and builds off a lot of other modular things, so `ax_client.generation_strategy.model.model.surrogate.model` doesn't seem too crazy to me 😉, especially for the more chemistry-specific use-cases I've had. Here's what seemed to do the trick, at least for extracting the `feature_importances`:
For:
```python
fig = plot_feature_importance_by_feature_plotly(botorch_model)
```
I still get an error:

> ```python
> mdl = ax_client.generation_strategy.model.model.surrogate.model
> botorch_model = BotorchModel()
> botorch_model.model = mdl
> botorch_model.feature_importances()
> ```python
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "c:\users\sterg\documents\github\sparks-baird\ax\ax\plot\feature_importances.py", line 147, in plot_feature_importance_by_feature_plotly
>     raise NotImplementedError("No traces found for metric")
> NotImplementedError: No traces found for metric
> ```

but it's not as big of a deal for me since the main thing was being able to get the ARD-based feature importances.

**Comment by Balandat** [comment]
One thing that is clear from this is that we are definitely heavily overloading the term "model" :)
