### ISSUE TITLE
[QUESTION] How to add measurement noise to the sampling strategy

### ISSUE THREAD

**Issue by farrokhsiar** [facebook/Ax#827]
I am curious, is there any way to include the knowledge of the measurement noise into the sampling strategy, such as GPEI?

**Comment by bernardbeckerman** [comment]
Hi @farrokhsiar, there sure is! However, it depends on the API you're using. For example, in the loop API, this can be achieved by supplying a tuple `(mean, noise)` in place of the usual raw number for `mean` (although instead of the term `noise` we usually use `sem` - standard error of the mean). See [here](https://ax.dev/tutorials/gpei_hartmann_loop.html#1.-Define-evaluation-function) for an example, in which the errors of both metrics are set to `0.0` - you would instead set it to whatever your measurement noise is. Let me know if you're using a different API and/or take a look through our docs and tutorials for other examples. Hope that helps!

**Comment by farrokhsiar** [comment]
Thanks. I am using the service API. So this means when using the complete_trial, method, I should add `sem` as well as the `mean`?

**Comment by bernardbeckerman** [comment]
Yes, the service API works similarly to the loop API in this regard. Simply specify the output of your evaluation function following [this example](https://ax.dev/tutorials/gpei_hartmann_service.html#3.-Define-how-to-evaluate-trials), e.g.,

```
return {"my_metric_1": (metric_1_mean, metric_1_sem), "my_metric_2": (metric_2_mean, metric_2_sem)}
```

where all means and sems are calculated in the body of your function. Let me know if that helps!

**Comment by farrokhsiar** [comment]
Thanks. It did solve my question. By the way, could you look into #828?

**Comment by bernardbeckerman** [comment]
Great! And sure, I'll take a look : )

**Comment by bernardbeckerman** [comment]
Ah, the people tagged on that should be the best ones to answer : )
