### ISSUE TITLE
SQLAlchemy ``cache_ok`` bit

### ISSUE THREAD

**Issue by farrokhsiar** [facebook/Ax#873]
While working with an RDS database, I received this warning, and the performance has deteriorated, from the local version, drastically:   
`.....lib/python3.8/site-packages/ax/storage/sqa_store/load.py:229: SAWarning:
TypeDecorator JSONEncodedText() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)`
Any idea on how I can address it?

**Comment by danielcohenlive** [comment]
Thanks for pointing this out.  When do you get this warning?  Can you give instructions on how to reproduce it?

Also, I would think the extra time wouldn't be very significant compared to other operations that Ax does.  Is it noticeably slow?  Ax isn't doing frequent reads.

**Comment by farrokhsiar** [comment]
Let me add a bit of context:
I am working to develop a CRUD app using AX, which is basically AX+Dash interface. I have two versions of the App, one works with a local PostgresSQL and one with RDS backend. Anytime a new experiment is added, I update the list by asking AX to read from the database. On the local version, I don't receive any cash_ok warning, and it updates in a fraction of a second. On the one with the RDS backend, it takes more than 5 seconds to update after each click, which makes it clunky.

**Comment by alxfed** [comment]
Unfortunately it happens in 0.2.5.1 too, but on line 232 now
`/storage/sqa_store/load.py:232: SAWarning: TypeDecorator JSONEncodedText() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  .one_or_none()`
