### ISSUE TITLE
MultiObjective.clone() resets objective weights.

### ISSUE THREAD

**Issue by soerenjalas** [facebook/Ax#883]
Hi,
I stumbled across this while trying to figure out #870. When `MultiObjective.clone()` is called `MultiObjective.weights` is not copied to the new instance which then automatically gets unit weights. 
Since `MultiObjective.clone()` is called during the transformation of the optimization config this prevents to communicate the correct objective weights to the acquisition function when using the service API. 

Would there be any obvious problems with doing something like 

```python
def clone(self) -> Objective:
        """Create a copy of the objective."""
        copy = MultiObjective(objectives=[o.clone() for o in self.objectives])
        copy.weights = self.weights
        return copy
```

Thanks and sorry if I'm missing something here.

**Comment by EugenHotaj** [comment]
@soerenjalas Thanks for the issue. The comments in the code, [e.g. here](https://github.com/facebook/Ax/blob/main/ax/core/objective.py#L101) seem to indicate that this is intentional for `MultiObjective`. However, [ScalarizedObjective](https://github.com/facebook/Ax/blob/main/ax/core/objective.py#L180) does indeed allow you to set the weights and copies them appropriately. Maybe this is also what you're also looking for in #870?

**Comment by EugenHotaj** [comment]
> There is no way to tell AxClient.create_experiment to use a ScalarizedObjective directly, correct?

@soerenjalas  Doesn't look like there is an easy way to pass `OptimizationConfig` when calling `create_experiment`, @lena-kashtelyan maybe it makes sense to expose this?

In any case, looks like [`AxClient.set_optimization_config`](https://github.com/facebook/Ax/blob/main/ax/service/ax_client.py#L389) is what you want. It pretty much does the same thing you did manually.
